(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Photonless Weak twogenerations",
  Authors -> {"S. Song"},
  Version -> "1.0.3",
  Date -> "06. 06. 2024",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"}};

FR$ClassesTranslation={H -> S[1], Chi1 -> S[2], Chi2 -> S[3], Chi3 -> S[4], W1 -> V[1], W2 -> V[2], W3 -> V[3], c1 -> U[1], c2 -> U[2], c3 -> U[3], u -> F[1], c -> F[2], d -> F[3], s -> F[4]};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={S[2], S[3], S[4]};

(*     Declared indices    *)

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

IndexRange[ Index[Generation] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi1" },

S[3] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi2" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi3" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W1" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W2" },

V[3] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W3" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c1" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c2" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c3" },

F[1] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu,
    Indices -> {},
    PropagatorLabel -> "u" },

F[2] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mc,
    Indices -> {},
    PropagatorLabel -> "c" },

F[3] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md,
    Indices -> {},
    PropagatorLabel -> "d" },

F[4] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ms,
    Indices -> {},
    PropagatorLabel -> "s" }
}


(*        Definitions       *)


mh[ ___ ] := mh;
mW[ ___ ] := mW;
Mu[ ___ ] := Mu;
Mc[ ___ ] := Mc;
Md[ ___ ] := Md;
Ms[ ___ ] := Ms;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[3] , S[3] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[4] , S[4] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[4] , S[4] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[1] , S[1] ] == {{0, (-I)*mh*(2*FR$delta[{mh}, {}] + mh*FR$deltaZ[{H, H}, {{}}])}, {0, (-I)*FR$deltaZ[{H, H}, {{}}]}},

C[ S[2] , S[2] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi1, Chi1}, {{}}]}},

C[ S[3] , S[3] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi2, Chi2}, {{}}]}},

C[ S[4] , S[4] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi3, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[3] , S[3] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[4] , S[4] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lambda*vH, ((-3*I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 3*mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[2] , V[1] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*FR$deltaZ[{W1, W1}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*FR$deltaZ[{W1, W1}, {{}}])/2}},

C[ V[1] , V[1] ] == {{0, (-I)*FR$deltaZ[{W1, W1}, {{}}]}, {0, I*FR$deltaZ[{W1, W1}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W1, W1}, {{}}])}, {0, I*FR$deltaZ[{W1, W1}, {{}}]}},

C[ S[3] , V[2] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*FR$deltaZ[{W2, W2}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*FR$deltaZ[{W2, W2}, {{}}])/2}},

C[ V[2] , V[2] ] == {{0, (-I)*FR$deltaZ[{W2, W2}, {{}}]}, {0, I*FR$deltaZ[{W2, W2}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W2, W2}, {{}}])}, {0, I*FR$deltaZ[{W2, W2}, {{}}]}},

C[ S[4] , V[3] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*FR$deltaZ[{W3, W3}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*FR$deltaZ[{W3, W3}, {{}}])/2}},

C[ V[3] , V[3] ] == {{0, (-I)*FR$deltaZ[{W3, W3}, {{}}]}, {0, I*FR$deltaZ[{W3, W3}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W3, W3}, {{}}])}, {0, I*FR$deltaZ[{W3, W3}, {{}}]}},

C[ -U[1] , U[1] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[1] , U[1] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[4] , -U[1] , U[2] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/mW}},

C[ -U[1] , U[2] , V[3] ] == {{gc28, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc28, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[3] , -U[1] , U[3] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/mW}},

C[ -U[1] , U[3] , V[2] ] == {{gc30, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {gc30, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {0, 0}},

C[ S[4] , -U[2] , U[1] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/mW}},

C[ -U[2] , U[1] , V[3] ] == {{gc32, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc32, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {0, 0}},

C[ -U[2] , U[2] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[2] , -U[2] , U[3] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/mW}},

C[ -U[2] , U[3] , V[1] ] == {{gc36, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(2*mW*vH)}, {gc36, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/mW}},

C[ -U[3] , U[1] , V[2] ] == {{gc38, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(2*mW*vH)}, {gc38, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[2] , -U[3] , U[2] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/mW}},

C[ -U[3] , U[2] , V[1] ] == {{gc40, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {gc40, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {0, 0}},

C[ -U[3] , U[3] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[3] , U[3] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[2] , S[2] , S[2] , S[3] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[3] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[4] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[3] , V[1] ] == {{0, (mW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/2}},

C[ S[3] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, Chi2}, {{}}]}},

C[ S[3] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[2] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[4] , V[1] ] == {{0, (mW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/2}},

C[ S[4] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[2] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi1, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi1, H}, {{}}] + 3*FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[1] , V[1] ] == {{0, (mW*FR$deltaZ[{Chi1, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi1, H}, {{}}])/2}},

C[ S[1] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, H}, {{}}]}},

C[ S[1] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, H}, {{}}]}},

C[ S[2] , V[2] ] == {{0, (mW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/2}},

C[ S[2] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, Chi1}, {{}}]}},

C[ S[2] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, Chi1}, {{}}]}},

C[ S[2] , S[2] , S[3] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[3] , S[3] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[4] , V[2] ] == {{0, (mW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}]))/2}},

C[ S[4] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[3] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[3] , S[3] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi2, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi2}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi2, H}, {{}}] + 3*FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[1] , V[2] ] == {{0, (mW*FR$deltaZ[{Chi2, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi2, H}, {{}}])/2}},

C[ S[1] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, H}, {{}}]}},

C[ S[1] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, H}, {{}}]}},

C[ S[2] , V[3] ] == {{0, (mW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{W1, W3}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{W1, W3}, {{}}]))/2}},

C[ S[2] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, Chi1}, {{}}]}},

C[ S[2] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, Chi1}, {{}}]}},

C[ S[3] , V[3] ] == {{0, (mW*(FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/2}},

C[ S[3] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, Chi2}, {{}}]}},

C[ S[3] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[3] , S[3] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[4] , S[4] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi3, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi3}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi3, H}, {{}}] + 3*FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[1] , V[3] ] == {{0, (mW*FR$deltaZ[{Chi3, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi3, H}, {{}}])/2}},

C[ S[1] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, H}, {{}}]}},

C[ S[1] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, H}, {{}}]}},

C[ S[2] , S[2] , S[2] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[3] , S[3] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[4] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[2] , S[3] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , S[3] , S[3] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , S[4] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[3] , S[3] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[2] ] == {{0, (-1/2*I)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ -U[2] , U[3] , V[2] ] == {{0, (gW*FR$deltaZ[{W1, W2}, {{}}])/2}, {0, (gW*FR$deltaZ[{W1, W2}, {{}}])/2}, {0, 0}},

C[ -U[3] , U[2] , V[2] ] == {{0, -1/2*(gW*FR$deltaZ[{W1, W2}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W1, W2}, {{}}])}, {0, 0}},

C[ V[1] , V[3] ] == {{0, (-1/2*I)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ -U[2] , U[3] , V[3] ] == {{0, (gW*FR$deltaZ[{W1, W3}, {{}}])/2}, {0, (gW*FR$deltaZ[{W1, W3}, {{}}])/2}, {0, 0}},

C[ -U[3] , U[2] , V[3] ] == {{0, -1/2*(gW*FR$deltaZ[{W1, W3}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W1, W3}, {{}}])}, {0, 0}},

C[ -U[1] , U[3] , V[1] ] == {{0, -1/2*(gW*FR$deltaZ[{W2, W1}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W2, W1}, {{}}])}, {0, 0}},

C[ -U[3] , U[1] , V[1] ] == {{0, (gW*FR$deltaZ[{W2, W1}, {{}}])/2}, {0, (gW*FR$deltaZ[{W2, W1}, {{}}])/2}, {0, 0}},

C[ V[2] , V[3] ] == {{0, (-1/2*I)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ -U[1] , U[3] , V[3] ] == {{0, -1/2*(gW*FR$deltaZ[{W2, W3}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W2, W3}, {{}}])}, {0, 0}},

C[ -U[3] , U[1] , V[3] ] == {{0, (gW*FR$deltaZ[{W2, W3}, {{}}])/2}, {0, (gW*FR$deltaZ[{W2, W3}, {{}}])/2}, {0, 0}},

C[ -U[1] , U[2] , V[1] ] == {{0, (gW*FR$deltaZ[{W3, W1}, {{}}])/2}, {0, (gW*FR$deltaZ[{W3, W1}, {{}}])/2}, {0, 0}},

C[ -U[2] , U[1] , V[1] ] == {{0, -1/2*(gW*FR$deltaZ[{W3, W1}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W3, W1}, {{}}])}, {0, 0}},

C[ -U[1] , U[2] , V[2] ] == {{0, (gW*FR$deltaZ[{W3, W2}, {{}}])/2}, {0, (gW*FR$deltaZ[{W3, W2}, {{}}])/2}, {0, 0}},

C[ -U[2] , U[1] , V[2] ] == {{0, -1/2*(gW*FR$deltaZ[{W3, W2}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W3, W2}, {{}}])}, {0, 0}},

C[ -F[3] , F[3] ] == {{0, (-1/2*I)*(2*FR$delta[{Md}, {}] + Md*FR$deltaZ[{d, d}, {{}}, "L"] + Md*FR$deltaZ[{d, d}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Md}, {}] + Md*FR$deltaZ[{d, d}, {{}}, "L"] + Md*FR$deltaZ[{d, d}, {{}}, "R"])}, {0, I*FR$deltaZ[{d, d}, {{}}, "L"]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[4] , F[4] ] == {{0, (-1/2*I)*(2*FR$delta[{Ms}, {}] + Ms*FR$deltaZ[{s, s}, {{}}, "L"] + Ms*FR$deltaZ[{s, s}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Ms}, {}] + Ms*FR$deltaZ[{s, s}, {{}}, "L"] + Ms*FR$deltaZ[{s, s}, {{}}, "R"])}, {0, I*FR$deltaZ[{s, s}, {{}}, "L"]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[3] , F[2] ] == {{0, (-1/2*I)*(Mc*Conjugate[FR$deltaZ[{c, d}, {{}}, "R"]] + Md*FR$deltaZ[{d, c}, {{}}, "L"])}, {0, (-1/2*I)*(Mc*Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] + Md*FR$deltaZ[{d, c}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] + FR$deltaZ[{d, c}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, d}, {{}}, "R"]] + FR$deltaZ[{d, c}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[3] , F[4] ] == {{0, (-1/2*I)*(Ms*Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + Md*FR$deltaZ[{d, s}, {{}}, "L"])}, {0, (-1/2*I)*(Ms*Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + Md*FR$deltaZ[{d, s}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + FR$deltaZ[{d, s}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[3] , F[1] ] == {{0, (-1/2*I)*(Mu*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] + Md*FR$deltaZ[{d, u}, {{}}, "L"])}, {0, (-1/2*I)*(Mu*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + Md*FR$deltaZ[{d, u}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + FR$deltaZ[{d, u}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] + FR$deltaZ[{d, u}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[4] , F[2] ] == {{0, (-1/2*I)*(Mc*Conjugate[FR$deltaZ[{c, s}, {{}}, "R"]] + Ms*FR$deltaZ[{s, c}, {{}}, "L"])}, {0, (-1/2*I)*(Mc*Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] + Ms*FR$deltaZ[{s, c}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] + FR$deltaZ[{s, c}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, s}, {{}}, "R"]] + FR$deltaZ[{s, c}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[4] , F[3] ] == {{0, (-1/2*I)*(Md*Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + Ms*FR$deltaZ[{s, d}, {{}}, "L"])}, {0, (-1/2*I)*(Md*Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + Ms*FR$deltaZ[{s, d}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + FR$deltaZ[{s, d}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[4] , F[1] ] == {{0, (-1/2*I)*(Mu*Conjugate[FR$deltaZ[{u, s}, {{}}, "R"]] + Ms*FR$deltaZ[{s, u}, {{}}, "L"])}, {0, (-1/2*I)*(Mu*Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] + Ms*FR$deltaZ[{s, u}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] + FR$deltaZ[{s, u}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, s}, {{}}, "R"]] + FR$deltaZ[{s, u}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] ] == {{0, (-1/2*I)*(2*FR$delta[{Mc}, {}] + Mc*FR$deltaZ[{c, c}, {{}}, "L"] + Mc*FR$deltaZ[{c, c}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Mc}, {}] + Mc*FR$deltaZ[{c, c}, {{}}, "L"] + Mc*FR$deltaZ[{c, c}, {{}}, "R"])}, {0, I*FR$deltaZ[{c, c}, {{}}, "L"]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[1] , F[1] ] == {{0, (-1/2*I)*(2*FR$delta[{Mu}, {}] + Mu*FR$deltaZ[{u, u}, {{}}, "L"] + Mu*FR$deltaZ[{u, u}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Mu}, {}] + Mu*FR$deltaZ[{u, u}, {{}}, "L"] + Mu*FR$deltaZ[{u, u}, {{}}, "R"])}, {0, I*FR$deltaZ[{u, u}, {{}}, "L"]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[2] , F[3] ] == {{0, (-1/2*I)*(Md*Conjugate[FR$deltaZ[{d, c}, {{}}, "R"]] + Mc*FR$deltaZ[{c, d}, {{}}, "L"])}, {0, (-1/2*I)*(Md*Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] + Mc*FR$deltaZ[{c, d}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] + FR$deltaZ[{c, d}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, c}, {{}}, "R"]] + FR$deltaZ[{c, d}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[2] , F[4] ] == {{0, (-1/2*I)*(Ms*Conjugate[FR$deltaZ[{s, c}, {{}}, "R"]] + Mc*FR$deltaZ[{c, s}, {{}}, "L"])}, {0, (-1/2*I)*(Ms*Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] + Mc*FR$deltaZ[{c, s}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] + FR$deltaZ[{c, s}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, c}, {{}}, "R"]] + FR$deltaZ[{c, s}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] ] == {{0, (-1/2*I)*(Mu*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + Mc*FR$deltaZ[{c, u}, {{}}, "L"])}, {0, (-1/2*I)*(Mu*Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + Mc*FR$deltaZ[{c, u}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + FR$deltaZ[{c, u}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] ] == {{0, (-1/2*I)*(Mc*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + Mu*FR$deltaZ[{u, c}, {{}}, "L"])}, {0, (-1/2*I)*(Mc*Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + Mu*FR$deltaZ[{u, c}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + FR$deltaZ[{u, c}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[1] , F[3] ] == {{0, (-1/2*I)*(Md*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + Mu*FR$deltaZ[{u, d}, {{}}, "L"])}, {0, (-1/2*I)*(Md*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + Mu*FR$deltaZ[{u, d}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + FR$deltaZ[{u, d}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + FR$deltaZ[{u, d}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[1] , F[4] ] == {{0, (-1/2*I)*(Ms*Conjugate[FR$deltaZ[{s, u}, {{}}, "R"]] + Mu*FR$deltaZ[{u, s}, {{}}, "L"])}, {0, (-1/2*I)*(Ms*Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] + Mu*FR$deltaZ[{u, s}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] + FR$deltaZ[{u, s}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, u}, {{}}, "R"]] + FR$deltaZ[{u, s}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ S[2] , S[1] , V[1] ] == {{-gc155, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(4*mW*vH)}, {gc155, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[1] ] == {{-gc156, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {gc156, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(4*mW*vH)}},

C[ S[3] , S[1] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] - FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] - FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))}},

C[ S[4] , S[1] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))}},

C[ S[2] , S[4] , V[1] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] - FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W2, W1}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] - FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W2, W1}, {{}}]))/4}},

C[ S[2] , S[3] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W3, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W3, W1}, {{}}]))}},

C[ S[2] , S[2] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[1] , V[1] , V[1] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/mW}},

C[ S[2] , S[3] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[2] , S[4] , V[2] ] == {{-gc175, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(4*mW*vH)}, {gc175, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[1] , V[2] ] == {{-gc176, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(4*mW*vH)}, {gc176, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W1, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W1, W2}, {{}}]))}},

C[ S[4] , S[1] , V[2] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi1, H}, {{}}] - FR$deltaZ[{Chi2, Chi3}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi1, H}, {{}}] - FR$deltaZ[{Chi2, Chi3}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))/4}},

C[ S[2] , S[1] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))}},

C[ S[2] , S[3] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi3, Chi2}, {{}}] - FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi3, Chi2}, {{}}] - FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))}},

C[ S[2] , S[2] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[3] , S[3] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[4] , S[4] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[1] , V[1] , V[2] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ V[1] , V[2] , V[3] ] == {{-gc186, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc186, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc186, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {-gc186, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {-gc186, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc186, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[1] , V[2] , V[2] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/mW}},

C[ S[2] , S[3] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[1] , V[2] , V[2] ] == {{(-I)*gc201, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {(-I)*gc201, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {(2*I)*gc201, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[2] , S[3] , V[3] ] == {{-gc202, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc202, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(4*mW*vH)}},

C[ S[4] , S[1] , V[3] ] == {{-gc203, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(4*mW*vH)}, {gc203, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[3] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] - FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] - FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))}},

C[ S[3] , S[1] , V[3] ] == {{0, (gW*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))}},

C[ S[2] , S[4] , V[3] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W2, W3}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W2, W3}, {{}}]))/4}},

C[ S[2] , S[1] , V[3] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, H}, {{}}] - FR$deltaZ[{Chi3, Chi1}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, H}, {{}}] - FR$deltaZ[{Chi3, Chi1}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))/4}},

C[ S[2] , S[2] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[3] , S[3] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[4] , S[4] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[1] , S[1] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[1] , V[1] , V[3] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[2] , S[2] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[3] , S[3] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[4] , S[4] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[1] , S[1] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[1] , V[2] , V[3] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ V[1] , V[1] , V[2] , V[3] ] == {{0, (I/2)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (-I)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ V[1] , V[2] , V[2] , V[3] ] == {{0, (-I)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[2] , S[2] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[1] , V[3] , V[3] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/mW}},

C[ S[2] , S[3] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[1] , V[3] , V[3] ] == {{(-I)*gc234, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(-I)*gc234, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(2*I)*gc234, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ V[1] , V[2] , V[3] , V[3] ] == {{0, (I/2)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (-I)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ V[2] , V[2] , V[3] , V[3] ] == {{(-I)*gc236, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(-I)*gc236, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(2*I)*gc236, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ -F[3] , F[1] , S[2] ] == {{gc237L, (yd1*(2*vH*FR$delta[{Md}, {}] - 2*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + I*Md*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Md*vH*FR$deltaZ[{d, d}, {{}}, "R"] + Md*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(2*Sqrt[2]*Md*vH)}, {gc237R, -1/2*(yu1*(2*vH*FR$delta[{Mu}, {}] - 2*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + I*Mu*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Mu*vH*FR$deltaZ[{d, d}, {{}}, "L"] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(Sqrt[2]*Mu*vH)}},

C[ -F[3] , F[1] , S[3] ] == {{I*gc238L, (yd1*((2*I)*vH*FR$delta[{Md}, {}] - (2*I)*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] + I*Md*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + I*Md*vH*FR$deltaZ[{d, d}, {{}}, "R"] + I*Md*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(2*Sqrt[2]*Md*vH)}, {I*gc238R, -1/2*(yu1*((2*I)*vH*FR$delta[{Mu}, {}] - (2*I)*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] + I*Mu*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + I*Mu*vH*FR$deltaZ[{d, d}, {{}}, "L"] + I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(Sqrt[2]*Mu*vH)}},

C[ -F[3] , F[1] , S[4] ] == {{0, (yu1*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] + yd1*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yd1*FR$deltaZ[{Chi2, Chi3}, {{}}] - yd1*FR$deltaZ[{d, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu1*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + yu1*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yu1*FR$deltaZ[{Chi2, Chi3}, {{}}] - yd1*FR$deltaZ[{d, u}, {{}}, "R"])/Sqrt[2]}},

C[ -F[3] , F[1] , S[1] ] == {{0, ((-I)*yu1*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] + yd1*FR$deltaZ[{Chi1, H}, {{}}] + I*yd1*FR$deltaZ[{Chi2, H}, {{}}] - I*yd1*FR$deltaZ[{d, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] - I*yu1*FR$deltaZ[{Chi1, H}, {{}}] + yu1*FR$deltaZ[{Chi2, H}, {{}}] + yd1*FR$deltaZ[{d, u}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[3] , F[3] , S[4] ] == {{gc241L, -1/2*(yd1*(2*vH*FR$delta[{Md}, {}] - 2*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + I*Md*vH*FR$deltaZ[{H, Chi3}, {{}}] + Md*vH*FR$deltaZ[{d, d}, {{}}, "L"] + Md*vH*FR$deltaZ[{d, d}, {{}}, "R"]))/(Sqrt[2]*Md*vH)}, {gc241R, (yd1*(2*vH*FR$delta[{Md}, {}] - 2*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] - I*Md*vH*FR$deltaZ[{H, Chi3}, {{}}] + Md*vH*FR$deltaZ[{d, d}, {{}}, "L"] + Md*vH*FR$deltaZ[{d, d}, {{}}, "R"]))/(2*Sqrt[2]*Md*vH)}},

C[ -F[3] , F[3] , S[1] ] == {{I*gc242, -1/2*(yd1*((2*I)*vH*FR$delta[{Md}, {}] - (2*I)*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi3, H}, {{}}] + I*Md*vH*FR$deltaZ[{H, H}, {{}}] + I*Md*vH*FR$deltaZ[{d, d}, {{}}, "L"] + I*Md*vH*FR$deltaZ[{d, d}, {{}}, "R"]))/(Sqrt[2]*Md*vH)}, {I*gc242, (yd1*((-2*I)*vH*FR$delta[{Md}, {}] + (2*I)*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi3, H}, {{}}] - I*Md*vH*FR$deltaZ[{H, H}, {{}}] - I*Md*vH*FR$deltaZ[{d, d}, {{}}, "L"] - I*Md*vH*FR$deltaZ[{d, d}, {{}}, "R"]))/(2*Sqrt[2]*Md*vH)}},

C[ -F[3] , F[3] , S[2] ] == {{0, (yu1*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] - yd1*FR$deltaZ[{Chi3, Chi1}, {{}}] - I*yd1*FR$deltaZ[{H, Chi1}, {{}}] + yd1*FR$deltaZ[{u, d}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yd1*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] - yd1*FR$deltaZ[{Chi3, Chi1}, {{}}] + I*yd1*FR$deltaZ[{H, Chi1}, {{}}] + yu1*FR$deltaZ[{u, d}, {{}}, "R"])/Sqrt[2]}},

C[ -F[3] , F[3] , S[3] ] == {{0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] - I*yd1*FR$deltaZ[{Chi3, Chi2}, {{}}] + yd1*FR$deltaZ[{H, Chi2}, {{}}] - yd1*FR$deltaZ[{u, d}, {{}}, "L"]))/Sqrt[2]}, {0, (I*yd1*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + yd1*FR$deltaZ[{Chi3, Chi2}, {{}}] - I*yd1*FR$deltaZ[{H, Chi2}, {{}}] - I*yu1*FR$deltaZ[{u, d}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[3] , F[2] , S[2] ] == {{0, (yd2*Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + yd1*FR$deltaZ[{u, c}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu2*Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + yu1*FR$deltaZ[{u, c}, {{}}, "R"])/Sqrt[2]}},

C[ -F[3] , F[4] , S[2] ] == {{0, (yu2*Conjugate[FR$deltaZ[{c, d}, {{}}, "R"]] + yd1*FR$deltaZ[{u, s}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yd2*Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] + yu1*FR$deltaZ[{u, s}, {{}}, "R"])/Sqrt[2]}},

C[ -F[3] , F[2] , S[3] ] == {{0, ((I/2)*(yd2*Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + yd1*FR$deltaZ[{u, c}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + yu1*FR$deltaZ[{u, c}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[3] , F[4] , S[3] ] == {{0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{c, d}, {{}}, "R"]] - yd1*FR$deltaZ[{u, s}, {{}}, "L"]))/Sqrt[2]}, {0, ((I/2)*(yd2*Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] - yu1*FR$deltaZ[{u, s}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[3] , F[2] , S[4] ] == {{0, (yu2*Conjugate[FR$deltaZ[{c, d}, {{}}, "R"]] - yd1*FR$deltaZ[{d, c}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu2*Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] - yd1*FR$deltaZ[{d, c}, {{}}, "R"])/Sqrt[2]}},

C[ -F[3] , F[4] , S[4] ] == {{0, -1/2*(yd2*Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + yd1*FR$deltaZ[{d, s}, {{}}, "L"])/Sqrt[2]}, {0, (yd2*Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + yd1*FR$deltaZ[{d, s}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[3] , F[2] , S[1] ] == {{0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{c, d}, {{}}, "R"]] + yd1*FR$deltaZ[{d, c}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] + yd1*FR$deltaZ[{d, c}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[3] , F[4] , S[1] ] == {{0, ((-1/2*I)*(yd2*Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + yd1*FR$deltaZ[{d, s}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yd2*Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + yd1*FR$deltaZ[{d, s}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[1] , S[2] ] == {{0, (yd1*Conjugate[FR$deltaZ[{d, c}, {{}}, "R"]] + yu2*FR$deltaZ[{s, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu1*Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] + yd2*FR$deltaZ[{s, u}, {{}}, "R"])/Sqrt[2]}},

C[ -F[4] , F[1] , S[2] ] == {{0, (yd1*Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + yd2*FR$deltaZ[{c, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu1*Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + yu2*FR$deltaZ[{c, u}, {{}}, "R"])/Sqrt[2]}},

C[ -F[1] , F[1] , S[2] ] == {{0, (yd1*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + yu1*FR$deltaZ[{Chi3, Chi1}, {{}}] - I*yu1*FR$deltaZ[{H, Chi1}, {{}}] + yu1*FR$deltaZ[{d, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu1*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + yu1*FR$deltaZ[{Chi3, Chi1}, {{}}] + I*yu1*FR$deltaZ[{H, Chi1}, {{}}] + yd1*FR$deltaZ[{d, u}, {{}}, "R"])/Sqrt[2]}},

C[ -F[2] , F[1] , S[3] ] == {{0, ((I/2)*(yd1*Conjugate[FR$deltaZ[{d, c}, {{}}, "R"]] - yu2*FR$deltaZ[{s, u}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] - yd2*FR$deltaZ[{s, u}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[4] , F[1] , S[3] ] == {{0, ((I/2)*(yd1*Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + yd2*FR$deltaZ[{c, u}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + yu2*FR$deltaZ[{c, u}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[1] , F[1] , S[3] ] == {{0, (I*yd1*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + yu1*FR$deltaZ[{Chi3, Chi2}, {{}}] - I*yu1*FR$deltaZ[{H, Chi2}, {{}}] - I*yu1*FR$deltaZ[{d, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] - I*yu1*FR$deltaZ[{Chi3, Chi2}, {{}}] + yu1*FR$deltaZ[{H, Chi2}, {{}}] - yd1*FR$deltaZ[{d, u}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[3] , S[4] ] == {{0, -1/2*(yd1*Conjugate[FR$deltaZ[{d, c}, {{}}, "R"]] - yu2*FR$deltaZ[{c, d}, {{}}, "L"])/Sqrt[2]}, {0, (yd1*Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] - yu2*FR$deltaZ[{c, d}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[4] , F[3] , S[4] ] == {{0, -1/2*(yd1*Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + yd2*FR$deltaZ[{s, d}, {{}}, "L"])/Sqrt[2]}, {0, (yd1*Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + yd2*FR$deltaZ[{s, d}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[1] , F[3] , S[4] ] == {{0, -1/2*(yd1*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] - yu1*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yu1*FR$deltaZ[{Chi2, Chi3}, {{}}] - yu1*FR$deltaZ[{u, d}, {{}}, "L"])/Sqrt[2]}, {0, (yd1*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] - yd1*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yd1*FR$deltaZ[{Chi2, Chi3}, {{}}] - yu1*FR$deltaZ[{u, d}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[2] , F[3] , S[1] ] == {{0, ((-1/2*I)*(yd1*Conjugate[FR$deltaZ[{d, c}, {{}}, "R"]] + yu2*FR$deltaZ[{c, d}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yd1*Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] + yu2*FR$deltaZ[{c, d}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[4] , F[3] , S[1] ] == {{0, ((-1/2*I)*(yd1*Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + yd2*FR$deltaZ[{s, d}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yd1*Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + yd2*FR$deltaZ[{s, d}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[1] , F[3] , S[1] ] == {{0, ((-I)*yd1*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + yu1*FR$deltaZ[{Chi1, H}, {{}}] - I*yu1*FR$deltaZ[{Chi2, H}, {{}}] - I*yu1*FR$deltaZ[{u, d}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yd1*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] - I*yd1*FR$deltaZ[{Chi1, H}, {{}}] - yd1*FR$deltaZ[{Chi2, H}, {{}}] + yu1*FR$deltaZ[{u, d}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[1] , F[3] , S[2] ] == {{gc265L, (yu1*(2*vH*FR$delta[{Mu}, {}] - 2*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] - I*Mu*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Mu*vH*FR$deltaZ[{d, d}, {{}}, "L"] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(2*Sqrt[2]*Mu*vH)}, {gc265R, -1/2*(yd1*(2*vH*FR$delta[{Md}, {}] - 2*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] - I*Md*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Md*vH*FR$deltaZ[{d, d}, {{}}, "R"] + Md*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(Sqrt[2]*Md*vH)}},

C[ -F[1] , F[3] , S[3] ] == {{I*gc266L, (yu1*((-2*I)*vH*FR$delta[{Mu}, {}] + (2*I)*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] - I*Mu*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] - I*Mu*vH*FR$deltaZ[{d, d}, {{}}, "L"] - I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(2*Sqrt[2]*Mu*vH)}, {I*gc266R, -1/2*(yd1*((-2*I)*vH*FR$delta[{Md}, {}] + (2*I)*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] - I*Md*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] - I*Md*vH*FR$deltaZ[{d, d}, {{}}, "R"] - I*Md*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(Sqrt[2]*Md*vH)}},

C[ -F[1] , F[2] , S[2] ] == {{0, (yd2*Conjugate[FR$deltaZ[{s, u}, {{}}, "R"]] + yu1*FR$deltaZ[{d, c}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu2*Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] + yd1*FR$deltaZ[{d, c}, {{}}, "R"])/Sqrt[2]}},

C[ -F[1] , F[4] , S[2] ] == {{0, (yu2*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + yu1*FR$deltaZ[{d, s}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yd2*Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + yd1*FR$deltaZ[{d, s}, {{}}, "R"])/Sqrt[2]}},

C[ -F[1] , F[2] , S[3] ] == {{0, ((I/2)*(yd2*Conjugate[FR$deltaZ[{s, u}, {{}}, "R"]] - yu1*FR$deltaZ[{d, c}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] - yd1*FR$deltaZ[{d, c}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[1] , F[4] , S[3] ] == {{0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + yu1*FR$deltaZ[{d, s}, {{}}, "L"]))/Sqrt[2]}, {0, ((I/2)*(yd2*Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + yd1*FR$deltaZ[{d, s}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[3] , S[2] ] == {{0, (yu1*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + yu2*FR$deltaZ[{s, d}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yd1*Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + yd2*FR$deltaZ[{s, d}, {{}}, "R"])/Sqrt[2]}},

C[ -F[4] , F[3] , S[2] ] == {{0, (yu1*Conjugate[FR$deltaZ[{u, s}, {{}}, "R"]] + yd2*FR$deltaZ[{c, d}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yd1*Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] + yu2*FR$deltaZ[{c, d}, {{}}, "R"])/Sqrt[2]}},

C[ -F[2] , F[3] , S[3] ] == {{0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + yu2*FR$deltaZ[{s, d}, {{}}, "L"]))/Sqrt[2]}, {0, ((I/2)*(yd1*Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + yd2*FR$deltaZ[{s, d}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[4] , F[3] , S[3] ] == {{0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{u, s}, {{}}, "R"]] - yd2*FR$deltaZ[{c, d}, {{}}, "L"]))/Sqrt[2]}, {0, ((I/2)*(yd1*Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] - yu2*FR$deltaZ[{c, d}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[4] , F[2] , S[2] ] == {{gc275L, (yd2*(2*vH*FR$delta[{Ms}, {}] - 2*Ms*FR$delta[{vH}, {}] + Ms*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + I*Ms*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Ms*vH*FR$deltaZ[{c, c}, {{}}, "L"] + Ms*vH*FR$deltaZ[{s, s}, {{}}, "R"]))/(2*Sqrt[2]*Ms*vH)}, {gc275R, -1/2*(yu2*(2*vH*FR$delta[{Mc}, {}] - 2*Mc*FR$delta[{vH}, {}] + Mc*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + I*Mc*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Mc*vH*FR$deltaZ[{c, c}, {{}}, "R"] + Mc*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(Sqrt[2]*Mc*vH)}},

C[ -F[4] , F[2] , S[3] ] == {{I*gc276L, (yd2*((2*I)*vH*FR$delta[{Ms}, {}] - (2*I)*Ms*FR$delta[{vH}, {}] + Ms*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] + I*Ms*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + I*Ms*vH*FR$deltaZ[{c, c}, {{}}, "L"] + I*Ms*vH*FR$deltaZ[{s, s}, {{}}, "R"]))/(2*Sqrt[2]*Ms*vH)}, {I*gc276R, -1/2*(yu2*((2*I)*vH*FR$delta[{Mc}, {}] - (2*I)*Mc*FR$delta[{vH}, {}] + Mc*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] + I*Mc*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + I*Mc*vH*FR$deltaZ[{c, c}, {{}}, "R"] + I*Mc*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(Sqrt[2]*Mc*vH)}},

C[ -F[4] , F[2] , S[4] ] == {{0, (yu2*Conjugate[FR$deltaZ[{c, s}, {{}}, "R"]] + yd2*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yd2*FR$deltaZ[{Chi2, Chi3}, {{}}] - yd2*FR$deltaZ[{s, c}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu2*Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] + yu2*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yu2*FR$deltaZ[{Chi2, Chi3}, {{}}] - yd2*FR$deltaZ[{s, c}, {{}}, "R"])/Sqrt[2]}},

C[ -F[4] , F[2] , S[1] ] == {{0, ((-I)*yu2*Conjugate[FR$deltaZ[{c, s}, {{}}, "R"]] + yd2*FR$deltaZ[{Chi1, H}, {{}}] + I*yd2*FR$deltaZ[{Chi2, H}, {{}}] - I*yd2*FR$deltaZ[{s, c}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] - I*yu2*FR$deltaZ[{Chi1, H}, {{}}] + yu2*FR$deltaZ[{Chi2, H}, {{}}] + yd2*FR$deltaZ[{s, c}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[4] , F[4] , S[4] ] == {{gc279L, -1/2*(yd2*(2*vH*FR$delta[{Ms}, {}] - 2*Ms*FR$delta[{vH}, {}] + Ms*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + I*Ms*vH*FR$deltaZ[{H, Chi3}, {{}}] + Ms*vH*FR$deltaZ[{s, s}, {{}}, "L"] + Ms*vH*FR$deltaZ[{s, s}, {{}}, "R"]))/(Sqrt[2]*Ms*vH)}, {gc279R, (yd2*(2*vH*FR$delta[{Ms}, {}] - 2*Ms*FR$delta[{vH}, {}] + Ms*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] - I*Ms*vH*FR$deltaZ[{H, Chi3}, {{}}] + Ms*vH*FR$deltaZ[{s, s}, {{}}, "L"] + Ms*vH*FR$deltaZ[{s, s}, {{}}, "R"]))/(2*Sqrt[2]*Ms*vH)}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc280, -1/2*(yd2*((2*I)*vH*FR$delta[{Ms}, {}] - (2*I)*Ms*FR$delta[{vH}, {}] + Ms*vH*FR$deltaZ[{Chi3, H}, {{}}] + I*Ms*vH*FR$deltaZ[{H, H}, {{}}] + I*Ms*vH*FR$deltaZ[{s, s}, {{}}, "L"] + I*Ms*vH*FR$deltaZ[{s, s}, {{}}, "R"]))/(Sqrt[2]*Ms*vH)}, {I*gc280, (yd2*((-2*I)*vH*FR$delta[{Ms}, {}] + (2*I)*Ms*FR$delta[{vH}, {}] + Ms*vH*FR$deltaZ[{Chi3, H}, {{}}] - I*Ms*vH*FR$deltaZ[{H, H}, {{}}] - I*Ms*vH*FR$deltaZ[{s, s}, {{}}, "L"] - I*Ms*vH*FR$deltaZ[{s, s}, {{}}, "R"]))/(2*Sqrt[2]*Ms*vH)}},

C[ -F[4] , F[4] , S[2] ] == {{0, (yu2*Conjugate[FR$deltaZ[{c, s}, {{}}, "R"]] - yd2*FR$deltaZ[{Chi3, Chi1}, {{}}] - I*yd2*FR$deltaZ[{H, Chi1}, {{}}] + yd2*FR$deltaZ[{c, s}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yd2*Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] - yd2*FR$deltaZ[{Chi3, Chi1}, {{}}] + I*yd2*FR$deltaZ[{H, Chi1}, {{}}] + yu2*FR$deltaZ[{c, s}, {{}}, "R"])/Sqrt[2]}},

C[ -F[4] , F[4] , S[3] ] == {{0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{c, s}, {{}}, "R"]] - I*yd2*FR$deltaZ[{Chi3, Chi2}, {{}}] + yd2*FR$deltaZ[{H, Chi2}, {{}}] - yd2*FR$deltaZ[{c, s}, {{}}, "L"]))/Sqrt[2]}, {0, (I*yd2*Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] + yd2*FR$deltaZ[{Chi3, Chi2}, {{}}] - I*yd2*FR$deltaZ[{H, Chi2}, {{}}] - I*yu2*FR$deltaZ[{c, s}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[4] , F[1] , S[4] ] == {{0, (yu1*Conjugate[FR$deltaZ[{u, s}, {{}}, "R"]] - yd2*FR$deltaZ[{s, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu1*Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] - yd2*FR$deltaZ[{s, u}, {{}}, "R"])/Sqrt[2]}},

C[ -F[4] , F[1] , S[1] ] == {{0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{u, s}, {{}}, "R"]] + yd2*FR$deltaZ[{s, u}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] + yd2*FR$deltaZ[{s, u}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[2] , S[2] ] == {{0, (yd2*Conjugate[FR$deltaZ[{s, c}, {{}}, "R"]] + yu2*FR$deltaZ[{Chi3, Chi1}, {{}}] - I*yu2*FR$deltaZ[{H, Chi1}, {{}}] + yu2*FR$deltaZ[{s, c}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu2*Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] + yu2*FR$deltaZ[{Chi3, Chi1}, {{}}] + I*yu2*FR$deltaZ[{H, Chi1}, {{}}] + yd2*FR$deltaZ[{s, c}, {{}}, "R"])/Sqrt[2]}},

C[ -F[2] , F[2] , S[3] ] == {{0, (I*yd2*Conjugate[FR$deltaZ[{s, c}, {{}}, "R"]] + yu2*FR$deltaZ[{Chi3, Chi2}, {{}}] - I*yu2*FR$deltaZ[{H, Chi2}, {{}}] - I*yu2*FR$deltaZ[{s, c}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] - I*yu2*FR$deltaZ[{Chi3, Chi2}, {{}}] + yu2*FR$deltaZ[{H, Chi2}, {{}}] - yd2*FR$deltaZ[{s, c}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[4] , S[4] ] == {{0, -1/2*(yd2*Conjugate[FR$deltaZ[{s, c}, {{}}, "R"]] - yu2*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yu2*FR$deltaZ[{Chi2, Chi3}, {{}}] - yu2*FR$deltaZ[{c, s}, {{}}, "L"])/Sqrt[2]}, {0, (yd2*Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] - yd2*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yd2*FR$deltaZ[{Chi2, Chi3}, {{}}] - yu2*FR$deltaZ[{c, s}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[1] , F[4] , S[4] ] == {{0, -1/2*(yd2*Conjugate[FR$deltaZ[{s, u}, {{}}, "R"]] - yu1*FR$deltaZ[{u, s}, {{}}, "L"])/Sqrt[2]}, {0, (yd2*Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] - yu1*FR$deltaZ[{u, s}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[2] , F[4] , S[1] ] == {{0, ((-I)*yd2*Conjugate[FR$deltaZ[{s, c}, {{}}, "R"]] + yu2*FR$deltaZ[{Chi1, H}, {{}}] - I*yu2*FR$deltaZ[{Chi2, H}, {{}}] - I*yu2*FR$deltaZ[{c, s}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yd2*Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] - I*yd2*FR$deltaZ[{Chi1, H}, {{}}] - yd2*FR$deltaZ[{Chi2, H}, {{}}] + yu2*FR$deltaZ[{c, s}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[1] , F[4] , S[1] ] == {{0, ((-1/2*I)*(yd2*Conjugate[FR$deltaZ[{s, u}, {{}}, "R"]] + yu1*FR$deltaZ[{u, s}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yd2*Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] + yu1*FR$deltaZ[{u, s}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[4] , S[2] ] == {{gc291L, (yu2*(2*vH*FR$delta[{Mc}, {}] - 2*Mc*FR$delta[{vH}, {}] + Mc*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] - I*Mc*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Mc*vH*FR$deltaZ[{c, c}, {{}}, "R"] + Mc*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(2*Sqrt[2]*Mc*vH)}, {gc291R, -1/2*(yd2*(2*vH*FR$delta[{Ms}, {}] - 2*Ms*FR$delta[{vH}, {}] + Ms*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] - I*Ms*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Ms*vH*FR$deltaZ[{c, c}, {{}}, "L"] + Ms*vH*FR$deltaZ[{s, s}, {{}}, "R"]))/(Sqrt[2]*Ms*vH)}},

C[ -F[2] , F[4] , S[3] ] == {{I*gc292L, (yu2*((-2*I)*vH*FR$delta[{Mc}, {}] + (2*I)*Mc*FR$delta[{vH}, {}] + Mc*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] - I*Mc*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] - I*Mc*vH*FR$deltaZ[{c, c}, {{}}, "R"] - I*Mc*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(2*Sqrt[2]*Mc*vH)}, {I*gc292R, -1/2*(yd2*((-2*I)*vH*FR$delta[{Ms}, {}] + (2*I)*Ms*FR$delta[{vH}, {}] + Ms*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] - I*Ms*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] - I*Ms*vH*FR$deltaZ[{c, c}, {{}}, "L"] - I*Ms*vH*FR$deltaZ[{s, s}, {{}}, "R"]))/(Sqrt[2]*Ms*vH)}},

C[ -F[1] , F[1] , S[4] ] == {{gc293L, (yu1*(2*vH*FR$delta[{Mu}, {}] - 2*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] - I*Mu*vH*FR$deltaZ[{H, Chi3}, {{}}] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "L"] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(2*Sqrt[2]*Mu*vH)}, {gc293R, -1/2*(yu1*(2*vH*FR$delta[{Mu}, {}] - 2*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + I*Mu*vH*FR$deltaZ[{H, Chi3}, {{}}] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "L"] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(Sqrt[2]*Mu*vH)}},

C[ -F[1] , F[1] , S[1] ] == {{I*gc294, (yu1*((-2*I)*vH*FR$delta[{Mu}, {}] + (2*I)*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi3, H}, {{}}] - I*Mu*vH*FR$deltaZ[{H, H}, {{}}] - I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "L"] - I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(2*Sqrt[2]*Mu*vH)}, {I*gc294, -1/2*(yu1*((2*I)*vH*FR$delta[{Mu}, {}] - (2*I)*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi3, H}, {{}}] + I*Mu*vH*FR$deltaZ[{H, H}, {{}}] + I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "L"] + I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(Sqrt[2]*Mu*vH)}},

C[ -F[1] , F[2] , S[4] ] == {{0, (yu2*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + yu1*FR$deltaZ[{u, c}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu2*Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + yu1*FR$deltaZ[{u, c}, {{}}, "R"])/Sqrt[2]}},

C[ -F[1] , F[2] , S[1] ] == {{0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + yu1*FR$deltaZ[{u, c}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yu2*Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + yu1*FR$deltaZ[{u, c}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[1] , S[4] ] == {{0, (yu1*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + yu2*FR$deltaZ[{c, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu1*Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + yu2*FR$deltaZ[{c, u}, {{}}, "R"])/Sqrt[2]}},

C[ -F[2] , F[1] , S[1] ] == {{0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + yu2*FR$deltaZ[{c, u}, {{}}, "L"]))/Sqrt[2]}, {0, ((-1/2*I)*(yu1*Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + yu2*FR$deltaZ[{c, u}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[2] , S[4] ] == {{gc299L, (yu2*(2*vH*FR$delta[{Mc}, {}] - 2*Mc*FR$delta[{vH}, {}] + Mc*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] - I*Mc*vH*FR$deltaZ[{H, Chi3}, {{}}] + Mc*vH*FR$deltaZ[{c, c}, {{}}, "L"] + Mc*vH*FR$deltaZ[{c, c}, {{}}, "R"]))/(2*Sqrt[2]*Mc*vH)}, {gc299R, -1/2*(yu2*(2*vH*FR$delta[{Mc}, {}] - 2*Mc*FR$delta[{vH}, {}] + Mc*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + I*Mc*vH*FR$deltaZ[{H, Chi3}, {{}}] + Mc*vH*FR$deltaZ[{c, c}, {{}}, "L"] + Mc*vH*FR$deltaZ[{c, c}, {{}}, "R"]))/(Sqrt[2]*Mc*vH)}},

C[ -F[2] , F[2] , S[1] ] == {{I*gc300, (yu2*((-2*I)*vH*FR$delta[{Mc}, {}] + (2*I)*Mc*FR$delta[{vH}, {}] + Mc*vH*FR$deltaZ[{Chi3, H}, {{}}] - I*Mc*vH*FR$deltaZ[{H, H}, {{}}] - I*Mc*vH*FR$deltaZ[{c, c}, {{}}, "L"] - I*Mc*vH*FR$deltaZ[{c, c}, {{}}, "R"]))/(2*Sqrt[2]*Mc*vH)}, {I*gc300, -1/2*(yu2*((2*I)*vH*FR$delta[{Mc}, {}] - (2*I)*Mc*FR$delta[{vH}, {}] + Mc*vH*FR$deltaZ[{Chi3, H}, {{}}] + I*Mc*vH*FR$deltaZ[{H, H}, {{}}] + I*Mc*vH*FR$deltaZ[{c, c}, {{}}, "L"] + I*Mc*vH*FR$deltaZ[{c, c}, {{}}, "R"]))/(Sqrt[2]*Mc*vH)}},

C[ -F[1] , F[3] , V[1] ] == {{I*gc301, (gW*((2*I)*vH*FR$delta[{mW}, {}] - (2*I)*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W1}, {{}}] + I*mW*vH*FR$deltaZ[{d, d}, {{}}, "L"] + I*mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[1] , F[3] , V[2] ] == {{gc302, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W2}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{d, d}, {{}}, "L"] + mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[1] , F[3] , V[3] ] == {{0, (gW*((-I)*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + I*FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W2, W3}, {{}}] + I*FR$deltaZ[{u, d}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[1] , F[2] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] + FR$deltaZ[{d, c}, {{}}, "L"])}, {0, 0}},

C[ -F[1] , F[4] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])}, {0, 0}},

C[ -F[1] , F[1] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + FR$deltaZ[{W3, W1}, {{}}] + FR$deltaZ[{d, u}, {{}}, "L"])}, {0, 0}},

C[ -F[2] , F[4] , V[1] ] == {{I*gc307, (gW*((2*I)*vH*FR$delta[{mW}, {}] - (2*I)*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W1}, {{}}] + I*mW*vH*FR$deltaZ[{c, c}, {{}}, "L"] + I*mW*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[2] , F[4] , V[2] ] == {{gc308, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W2}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{c, c}, {{}}, "L"] + mW*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[2] , F[4] , V[3] ] == {{0, (gW*((-I)*Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] + I*FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W2, W3}, {{}}] + I*FR$deltaZ[{c, s}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[2] , F[2] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] + FR$deltaZ[{W3, W1}, {{}}] + FR$deltaZ[{s, c}, {{}}, "L"])}, {0, 0}},

C[ -F[2] , F[3] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])}, {0, 0}},

C[ -F[2] , F[1] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] + FR$deltaZ[{s, u}, {{}}, "L"])}, {0, 0}},

C[ -F[3] , F[1] , V[1] ] == {{I*gc313, ((I/4)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + I*mW*vH*FR$deltaZ[{W2, W1}, {{}}] + mW*vH*FR$deltaZ[{d, d}, {{}}, "L"] + mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(mW*vH)}, {0, 0}},

C[ -F[3] , F[1] , V[2] ] == {{gc314, (gW*(-2*vH*FR$delta[{mW}, {}] + 2*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W2}, {{}}] - mW*vH*FR$deltaZ[{W2, W2}, {{}}] - mW*vH*FR$deltaZ[{d, d}, {{}}, "L"] - mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[3] , F[1] , V[3] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + FR$deltaZ[{W1, W3}, {{}}] + I*FR$deltaZ[{W2, W3}, {{}}] - FR$deltaZ[{d, u}, {{}}, "L"])}, {0, 0}},

C[ -F[3] , F[2] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])}, {0, 0}},

C[ -F[3] , F[3] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] - FR$deltaZ[{W3, W1}, {{}}] + FR$deltaZ[{u, d}, {{}}, "L"])}, {0, 0}},

C[ -F[3] , F[4] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] + FR$deltaZ[{u, s}, {{}}, "L"])}, {0, 0}},

C[ -F[4] , F[2] , V[1] ] == {{I*gc319, ((I/4)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + I*mW*vH*FR$deltaZ[{W2, W1}, {{}}] + mW*vH*FR$deltaZ[{c, c}, {{}}, "L"] + mW*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(mW*vH)}, {0, 0}},

C[ -F[4] , F[2] , V[2] ] == {{gc320, (gW*(-2*vH*FR$delta[{mW}, {}] + 2*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W2}, {{}}] - mW*vH*FR$deltaZ[{W2, W2}, {{}}] - mW*vH*FR$deltaZ[{c, c}, {{}}, "L"] - mW*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[4] , F[2] , V[3] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] + FR$deltaZ[{W1, W3}, {{}}] + I*FR$deltaZ[{W2, W3}, {{}}] - FR$deltaZ[{s, c}, {{}}, "L"])}, {0, 0}},

C[ -F[4] , F[3] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] + FR$deltaZ[{c, d}, {{}}, "L"])}, {0, 0}},

C[ -F[4] , F[4] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] - FR$deltaZ[{W3, W1}, {{}}] + FR$deltaZ[{c, s}, {{}}, "L"])}, {0, 0}},

C[ -F[4] , F[1] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])}, {0, 0}},

C[ -F[1] , F[2] , V[2] ] == {{0, -1/4*(gW*(Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] - FR$deltaZ[{d, c}, {{}}, "L"]))}, {0, 0}},

C[ -F[1] , F[4] , V[2] ] == {{0, (gW*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[1] , F[1] , V[2] ] == {{0, -1/4*(gW*(Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] - I*FR$deltaZ[{W3, W2}, {{}}] - FR$deltaZ[{d, u}, {{}}, "L"]))}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{0, -1/4*(gW*(Conjugate[FR$deltaZ[{s, c}, {{}}, "L"]] - I*FR$deltaZ[{W3, W2}, {{}}] - FR$deltaZ[{s, c}, {{}}, "L"]))}, {0, 0}},

C[ -F[2] , F[3] , V[2] ] == {{0, (gW*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[2] , F[1] , V[2] ] == {{0, -1/4*(gW*(Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] - FR$deltaZ[{s, u}, {{}}, "L"]))}, {0, 0}},

C[ -F[3] , F[2] , V[2] ] == {{0, -1/4*(gW*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"]))}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{0, (gW*(Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] - I*FR$deltaZ[{W3, W2}, {{}}] - FR$deltaZ[{u, d}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[3] , F[4] , V[2] ] == {{0, (gW*(Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] - FR$deltaZ[{u, s}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[4] , F[3] , V[2] ] == {{0, (gW*(Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] - FR$deltaZ[{c, d}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{0, (gW*(Conjugate[FR$deltaZ[{c, s}, {{}}, "L"]] - I*FR$deltaZ[{W3, W2}, {{}}] - FR$deltaZ[{c, s}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[4] , F[1] , V[2] ] == {{0, -1/4*(gW*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"]))}, {0, 0}},

C[ -F[1] , F[1] , V[3] ] == {{I*gc337, ((I/4)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}] + 2*mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(mW*vH)}, {0, 0}},

C[ -F[1] , F[2] , V[3] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{0, (-1/4*I)*gW*(Conjugate[FR$deltaZ[{s, u}, {{}}, "L"]] - FR$deltaZ[{u, s}, {{}}, "L"])}, {0, 0}},

C[ -F[2] , F[2] , V[3] ] == {{I*gc340, ((I/4)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}] + 2*mW*vH*FR$deltaZ[{c, c}, {{}}, "L"]))/(mW*vH)}, {0, 0}},

C[ -F[2] , F[3] , V[3] ] == {{0, (-1/4*I)*gW*(Conjugate[FR$deltaZ[{d, c}, {{}}, "L"]] - FR$deltaZ[{c, d}, {{}}, "L"])}, {0, 0}},

C[ -F[2] , F[1] , V[3] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])}, {0, 0}},

C[ -F[3] , F[3] , V[3] ] == {{I*gc343, ((-1/4*I)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}] + 2*mW*vH*FR$deltaZ[{d, d}, {{}}, "L"]))/(mW*vH)}, {0, 0}},

C[ -F[3] , F[2] , V[3] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{c, d}, {{}}, "L"]] - FR$deltaZ[{d, c}, {{}}, "L"])}, {0, 0}},

C[ -F[3] , F[4] , V[3] ] == {{0, (-1/4*I)*gW*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])}, {0, 0}},

C[ -F[4] , F[4] , V[3] ] == {{I*gc346, ((-1/4*I)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}] + 2*mW*vH*FR$deltaZ[{s, s}, {{}}, "L"]))/(mW*vH)}, {0, 0}},

C[ -F[4] , F[3] , V[3] ] == {{0, (-1/4*I)*gW*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])}, {0, 0}},

C[ -F[4] , F[1] , V[3] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{u, s}, {{}}, "L"]] - FR$deltaZ[{s, u}, {{}}, "L"])}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc28 -> gW,
     gc30 -> -gW,
     gc32 -> -gW,
     gc36 -> gW,
     gc38 -> gW,
     gc40 -> -gW,
     gc155 -> -1/2*gW,
     gc156 -> gW/2,
     gc175 -> -1/2*gW,
     gc176 -> -1/2*gW,
     gc186 -> -gW,
     gc201 -> -gW^2,
     gc202 -> gW/2,
     gc203 -> -1/2*gW,
     gc234 -> -gW^2,
     gc236 -> -gW^2,
     gc237L -> yd1/Sqrt[2],
     gc237R -> -(yu1/Sqrt[2]),
     gc238L -> yd1/Sqrt[2],
     gc238R -> -(yu1/Sqrt[2]),
     gc241L -> -(yd1/Sqrt[2]),
     gc241R -> yd1/Sqrt[2],
     gc242 -> -(yd1/Sqrt[2]),
     gc265L -> yu1/Sqrt[2],
     gc265R -> -(yd1/Sqrt[2]),
     gc266L -> -(yu1/Sqrt[2]),
     gc266R -> yd1/Sqrt[2],
     gc275L -> yd2/Sqrt[2],
     gc275R -> -(yu2/Sqrt[2]),
     gc276L -> yd2/Sqrt[2],
     gc276R -> -(yu2/Sqrt[2]),
     gc279L -> -(yd2/Sqrt[2]),
     gc279R -> yd2/Sqrt[2],
     gc280 -> -(yd2/Sqrt[2]),
     gc291L -> yu2/Sqrt[2],
     gc291R -> -(yd2/Sqrt[2]),
     gc292L -> -(yu2/Sqrt[2]),
     gc292R -> yd2/Sqrt[2],
     gc293L -> yu1/Sqrt[2],
     gc293R -> -(yu1/Sqrt[2]),
     gc294 -> -(yu1/Sqrt[2]),
     gc299L -> yu2/Sqrt[2],
     gc299R -> -(yu2/Sqrt[2]),
     gc300 -> -(yu2/Sqrt[2]),
     gc301 -> gW/2,
     gc302 -> gW/2,
     gc307 -> gW/2,
     gc308 -> gW/2,
     gc313 -> gW/2,
     gc314 -> -1/2*gW,
     gc319 -> gW/2,
     gc320 -> -1/2*gW,
     gc337 -> gW/2,
     gc340 -> gW/2,
     gc343 -> -1/2*gW,
     gc346 -> -1/2*gW};

