(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"PhiFour",
  Authors -> {"S. Song"},
  Version -> "1.0.0",
  Date -> "07. 06. 2024",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Phi",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mPhi,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    PropagatorLabel -> "Chi",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mChi,
    Indices -> {} }
}


(*        Definitions       *)


mPhi[ ___ ] := mPhi;
mChi[ ___ ] := mChi;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{(-I)*lambda42, (-I)*(FR$delta[{lambda42}, {}] + 2*lambda42*FR$deltaZ[{Chi, Chi}, {{}}])}},

C[ S[2] , -S[2] ] == {{0, (-I)*mChi*(2*FR$delta[{mChi}, {}] + mChi*FR$deltaZ[{Chi, Chi}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi, Chi}, {{}}]}},

C[ S[1] , S[1] ] == {{0, (-I)*mPhi*(2*FR$delta[{mPhi}, {}] + mPhi*FR$deltaZ[{Phi, Phi}, {{}}])}, {0, (-I)*FR$deltaZ[{Phi, Phi}, {{}}]}},

C[ S[1] , S[1] , S[1] ] == {{(-I)*lambda3, (-1/2*I)*(2*FR$delta[{lambda3}, {}] + 3*lambda3*FR$deltaZ[{Phi, Phi}, {{}}])}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-I)*lambda41, (-I)*(FR$delta[{lambda41}, {}] + 2*lambda41*FR$deltaZ[{Phi, Phi}, {{}}])}},

C[ S[2] , -S[2] , -S[2] , S[1] ] == {{0, (-1/2*I)*lambda42*FR$deltaZ[{Chi, Phi}, {{}}]}},

C[ -S[2] , S[1] ] == {{0, (-1/2*I)*mChi^2*FR$deltaZ[{Chi, Phi}, {{}}]}, {0, (-1/2*I)*FR$deltaZ[{Chi, Phi}, {{}}]}},

C[ S[2] , S[2] , -S[2] , S[1] ] == {{0, (-1/2*I)*lambda42*FR$deltaZ[{Chibar, Phi}, {{}}]}},

C[ S[2] , S[1] ] == {{0, (-1/2*I)*(mChi^2*FR$deltaZ[{Chibar, Phi}, {{}}] + mPhi^2*FR$deltaZ[{Phi, Chi}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chibar, Phi}, {{}}] + FR$deltaZ[{Phi, Chi}, {{}}])}},

C[ S[2] , S[1] , S[1] ] == {{0, (-1/2*I)*lambda3*FR$deltaZ[{Phi, Chi}, {{}}]}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{0, (-1/2*I)*lambda41*FR$deltaZ[{Phi, Chi}, {{}}]}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
};

