(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Simple Yukawa",
  Authors -> {"S. Song"},
  Version -> "1.0.0",
  Date -> "07. 06. 2024",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Phi",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mPhi,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    PropagatorLabel -> "Chi",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mChi,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    PropagatorLabel -> "Psi1",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mPsi1,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    PropagatorLabel -> "Psi2",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mPsi2,
    Indices -> {} }
}


(*        Definitions       *)


mPhi[ ___ ] := mPhi;
mChi[ ___ ] := mChi;
mPsi1[ ___ ] := mPsi1;
mPsi2[ ___ ] := mPsi2;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , -S[2] , -S[2] ] == {{(-I)*lambda42, (-I)*(FR$delta[{lambda42}, {}] + 2*lambda42*FR$deltaZ[{Chi, Chi}, {{}}])}},

C[ S[2] , -S[2] ] == {{0, (-I)*mChi*(2*FR$delta[{mChi}, {}] + mChi*FR$deltaZ[{Chi, Chi}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi, Chi}, {{}}]}},

C[ S[1] , S[1] ] == {{0, (-I)*mPhi*(2*FR$delta[{mPhi}, {}] + mPhi*FR$deltaZ[{Phi, Phi}, {{}}])}, {0, (-I)*FR$deltaZ[{Phi, Phi}, {{}}]}},

C[ S[1] , S[1] , S[1] ] == {{(-I)*lambda3, (-1/2*I)*(2*FR$delta[{lambda3}, {}] + 3*lambda3*FR$deltaZ[{Phi, Phi}, {{}}])}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-I)*lambda41, (-I)*(FR$delta[{lambda41}, {}] + 2*lambda41*FR$deltaZ[{Phi, Phi}, {{}}])}},

C[ S[2] , -S[2] , S[1] ] == {{(-I)*tau1, (-1/2*I)*(2*FR$delta[{tau1}, {}] + 2*tau1*FR$deltaZ[{Chi, Chi}, {{}}] + tau1*FR$deltaZ[{Phi, Phi}, {{}}])}},

C[ S[2] , -S[2] , S[1] , S[1] ] == {{(-I)*tau2, (-I)*(FR$delta[{tau2}, {}] + tau2*FR$deltaZ[{Chi, Chi}, {{}}] + tau2*FR$deltaZ[{Phi, Phi}, {{}}])}},

C[ -F[1] , F[1] ] == {{0, (-1/2*I)*(2*FR$delta[{mPsi1}, {}] + mPsi1*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + mPsi1*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{mPsi1}, {}] + mPsi1*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + mPsi1*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]] + 2*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]] + 2*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[1] , F[1] , S[1] ] == {{I*gc9, (-1/2*I)*(2*FR$delta[{Y1}, {}] + Y1*FR$deltaZ[{Phi, Phi}, {{}}] + Y1*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + Y1*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])}, {I*gc9, (-1/2*I)*(2*FR$delta[{Y1}, {}] + Y1*FR$deltaZ[{Phi, Phi}, {{}}] + Y1*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + Y1*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])}},

C[ -F[2] , F[2] ] == {{0, (-1/2*I)*(2*FR$delta[{mPsi2}, {}] + mPsi2*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] + mPsi2*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{mPsi2}, {}] + mPsi2*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] + mPsi2*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])}, {0, (I/2)*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]}, {0, (I/2)*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , S[1] ] == {{I*gc11, (-1/2*I)*(2*FR$delta[{Y2}, {}] + Y2*FR$deltaZ[{Phi, Phi}, {{}}] + Y2*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] + Y2*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])}, {I*gc11, (-1/2*I)*(2*FR$delta[{Y2}, {}] + Y2*FR$deltaZ[{Phi, Phi}, {{}}] + Y2*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] + Y2*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])}},

C[ S[2] , -S[2] , -S[2] , S[1] ] == {{0, (-1/2*I)*lambda42*FR$deltaZ[{Chi, Phi}, {{}}]}},

C[ -S[2] , S[1] ] == {{0, (-1/2*I)*mChi^2*FR$deltaZ[{Chi, Phi}, {{}}]}, {0, (-1/2*I)*FR$deltaZ[{Chi, Phi}, {{}}]}},

C[ -S[2] , S[1] , S[1] ] == {{0, (-I)*tau1*FR$deltaZ[{Chi, Phi}, {{}}]}},

C[ -S[2] , S[1] , S[1] , S[1] ] == {{0, ((-3*I)/2)*tau2*FR$deltaZ[{Chi, Phi}, {{}}]}},

C[ S[2] , S[2] , -S[2] , S[1] ] == {{0, (-1/2*I)*(lambda42*FR$deltaZ[{Chibar, Phi}, {{}}] + 2*tau2*FR$deltaZ[{Phi, Chi}, {{}}])}},

C[ S[2] , S[1] ] == {{0, (-1/2*I)*(mChi^2*FR$deltaZ[{Chibar, Phi}, {{}}] + mPhi^2*FR$deltaZ[{Phi, Chi}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chibar, Phi}, {{}}] + FR$deltaZ[{Phi, Chi}, {{}}])}},

C[ S[2] , S[1] , S[1] ] == {{0, (-1/2*I)*(2*tau1*FR$deltaZ[{Chibar, Phi}, {{}}] + lambda3*FR$deltaZ[{Phi, Chi}, {{}}])}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{0, (-1/2*I)*(3*tau2*FR$deltaZ[{Chibar, Phi}, {{}}] + lambda41*FR$deltaZ[{Phi, Chi}, {{}}])}},

C[ S[2] , S[2] , -S[2] ] == {{0, (-I)*tau1*FR$deltaZ[{Phi, Chi}, {{}}]}},

C[ -F[1] , F[1] , S[2] ] == {{0, (-1/2*I)*Y1*FR$deltaZ[{Phi, Chi}, {{}}]}, {0, (-1/2*I)*Y1*FR$deltaZ[{Phi, Chi}, {{}}]}},

C[ -F[2] , F[2] , S[2] ] == {{0, (-1/2*I)*Y2*FR$deltaZ[{Phi, Chi}, {{}}]}, {0, (-1/2*I)*Y2*FR$deltaZ[{Phi, Chi}, {{}}]}},

C[ -F[2] , F[1] ] == {{0, (-1/2*I)*(mPsi1*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]] + mPsi2*FR$deltaZ[{Psi2, Psi1}, {{}}, "L"])}, {0, (-1/2*I)*(mPsi1*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]] + mPsi2*FR$deltaZ[{Psi2, Psi1}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]] + FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + FR$deltaZ[{Psi2, Psi2}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]] + FR$deltaZ[{Psi1, Psi1}, {{}}, "R"] + FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] ] == {{0, (-1/2*I)*(mPsi2*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]] + mPsi1*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"])}, {0, (-1/2*I)*(mPsi2*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]] + mPsi1*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"])}, {0, (I/2)*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]}, {0, (I/2)*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] ] == {{0, (-1/2*I)*(Y2*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]] + Y1*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"])}, {0, (-1/2*I)*(Y2*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]] + Y1*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"])}},

C[ -F[2] , F[1] , S[1] ] == {{0, (-1/2*I)*(Y1*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]] + Y2*FR$deltaZ[{Psi2, Psi1}, {{}}, "L"])}, {0, (-1/2*I)*(Y1*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]] + Y2*FR$deltaZ[{Psi2, Psi1}, {{}}, "R"])}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc9 -> -Y1,
     gc11 -> -Y2};

