(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"QED Higgs Portal",
  Authors -> {"S.Song"},
  Version -> "1.0.1",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"},
  Date -> "26, Dec, 2024"};

FR$ClassesTranslation={h -> S[1], cc -> S[2], ele -> F[1], mu -> F[2], ta -> F[3], A -> V[1]};

FR$InteractionOrderPerturbativeExpansion={{New, 0}, {QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorType -> Dashing[{Small, Small}],
    PropagatorArrow -> None,
    Mass -> Mh,
    Indices -> {},
    PropagatorLabel -> "h" },

S[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {0},
    PropagatorType -> Dashing[{Small, Small}],
    PropagatorArrow -> Forward,
    Mass -> Mcc,
    Indices -> {},
    PropagatorLabel -> "cc" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mele,
    Indices -> {},
    PropagatorLabel -> "ele" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mmu,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mtau,
    Indices -> {},
    PropagatorLabel -> "ta" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" }
}


(*        Definitions       *)


Mh[ ___ ] := Mh;
Mcc[ ___ ] := Mcc;
Mele[ ___ ] := Mele;
Mmu[ ___ ] := Mmu;
Mtau[ ___ ] := Mtau;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , -S[2] , S[1] ] == {{(-I)*lambdacc, (-1/2*I)*lambdacc*(2*FR$deltaZ[{cc, cc}, {{}}] + FR$deltaZ[{h, h}, {{}}])}},

C[ S[2] , -S[2] ] == {{0, (-I)*Mcc*(2*FR$delta[{Mcc}, {}] + Mcc*FR$deltaZ[{cc, cc}, {{}}])}, {0, (-I)*FR$deltaZ[{cc, cc}, {{}}]}},

C[ S[1] , S[1] ] == {{0, (-I)*Mh*(2*FR$delta[{Mh}, {}] + Mh*FR$deltaZ[{h, h}, {{}}])}, {0, (-I)*FR$deltaZ[{h, h}, {{}}]}},

C[ V[1] , V[1] ] == {{0, (-I)*FR$deltaZ[{A, A}, {{}}]}, {0, I*FR$deltaZ[{A, A}, {{}}]}},

C[ -F[1] , F[1] ] == {{0, (-1/2*I)*(2*FR$delta[{Mele}, {}] + Mele*FR$deltaZ[{ele, ele}, {{}}, "L"] + Mele*FR$deltaZ[{ele, ele}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Mele}, {}] + Mele*FR$deltaZ[{ele, ele}, {{}}, "L"] + Mele*FR$deltaZ[{ele, ele}, {{}}, "R"])}, {0, I*FR$deltaZ[{ele, ele}, {{}}, "L"]}, {0, I*FR$deltaZ[{ele, ele}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[1] , F[1] , S[1] ] == {{I*gc6, (-1/2*I)*lambdah*(2*FR$delta[{Mele}, {}] + Mele*FR$deltaZ[{h, h}, {{}}] + Mele*FR$deltaZ[{ele, ele}, {{}}, "L"] + Mele*FR$deltaZ[{ele, ele}, {{}}, "R"])}, {I*gc6, (-1/2*I)*lambdah*(2*FR$delta[{Mele}, {}] + Mele*FR$deltaZ[{h, h}, {{}}] + Mele*FR$deltaZ[{ele, ele}, {{}}, "L"] + Mele*FR$deltaZ[{ele, ele}, {{}}, "R"])}},

C[ -F[2] , F[2] ] == {{0, (-1/2*I)*(2*FR$delta[{Mmu}, {}] + Mmu*FR$deltaZ[{mu, mu}, {{}}, "L"] + Mmu*FR$deltaZ[{mu, mu}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Mmu}, {}] + Mmu*FR$deltaZ[{mu, mu}, {{}}, "L"] + Mmu*FR$deltaZ[{mu, mu}, {{}}, "R"])}, {0, I*FR$deltaZ[{mu, mu}, {{}}, "L"]}, {0, I*FR$deltaZ[{mu, mu}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , S[1] ] == {{I*gc8, (-1/2*I)*lambdah*(2*FR$delta[{Mmu}, {}] + Mmu*FR$deltaZ[{h, h}, {{}}] + Mmu*FR$deltaZ[{mu, mu}, {{}}, "L"] + Mmu*FR$deltaZ[{mu, mu}, {{}}, "R"])}, {I*gc8, (-1/2*I)*lambdah*(2*FR$delta[{Mmu}, {}] + Mmu*FR$deltaZ[{h, h}, {{}}] + Mmu*FR$deltaZ[{mu, mu}, {{}}, "L"] + Mmu*FR$deltaZ[{mu, mu}, {{}}, "R"])}},

C[ -F[3] , F[3] ] == {{0, (-1/2*I)*(2*FR$delta[{Mtau}, {}] + Mtau*FR$deltaZ[{ta, ta}, {{}}, "L"] + Mtau*FR$deltaZ[{ta, ta}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Mtau}, {}] + Mtau*FR$deltaZ[{ta, ta}, {{}}, "L"] + Mtau*FR$deltaZ[{ta, ta}, {{}}, "R"])}, {0, I*FR$deltaZ[{ta, ta}, {{}}, "L"]}, {0, I*FR$deltaZ[{ta, ta}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[3] , F[3] , S[1] ] == {{I*gc10, (-1/2*I)*lambdah*(2*FR$delta[{Mtau}, {}] + Mtau*FR$deltaZ[{h, h}, {{}}] + Mtau*FR$deltaZ[{ta, ta}, {{}}, "L"] + Mtau*FR$deltaZ[{ta, ta}, {{}}, "R"])}, {I*gc10, (-1/2*I)*lambdah*(2*FR$delta[{Mtau}, {}] + Mtau*FR$deltaZ[{h, h}, {{}}] + Mtau*FR$deltaZ[{ta, ta}, {{}}, "L"] + Mtau*FR$deltaZ[{ta, ta}, {{}}, "R"])}},

C[ -F[1] , F[1] , V[1] ] == {{I*gc11, (I/2)*EL*(FR$deltaZ[{A, A}, {{}}] + 2*FR$deltaZ[{ele, ele}, {{}}, "L"])}, {I*gc11, (I/2)*EL*(FR$deltaZ[{A, A}, {{}}] + 2*FR$deltaZ[{ele, ele}, {{}}, "R"])}},

C[ -F[2] , F[2] , V[1] ] == {{I*gc12, (I/2)*EL*(FR$deltaZ[{A, A}, {{}}] + 2*FR$deltaZ[{mu, mu}, {{}}, "L"])}, {I*gc12, (I/2)*EL*(FR$deltaZ[{A, A}, {{}}] + 2*FR$deltaZ[{mu, mu}, {{}}, "R"])}},

C[ -F[3] , F[3] , V[1] ] == {{I*gc13, (I/2)*EL*(FR$deltaZ[{A, A}, {{}}] + 2*FR$deltaZ[{ta, ta}, {{}}, "L"])}, {I*gc13, (I/2)*EL*(FR$deltaZ[{A, A}, {{}}] + 2*FR$deltaZ[{ta, ta}, {{}}, "R"])}},

C[ -F[1] , F[2] ] == {{0, (-1/2*I)*(Mmu*Conjugate[FR$deltaZ[{mu, ele}, {{}}, "R"]] + Mele*FR$deltaZ[{ele, mu}, {{}}, "L"])}, {0, (-1/2*I)*(Mmu*Conjugate[FR$deltaZ[{mu, ele}, {{}}, "L"]] + Mele*FR$deltaZ[{ele, mu}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{mu, ele}, {{}}, "L"]] + FR$deltaZ[{ele, mu}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{mu, ele}, {{}}, "R"]] + FR$deltaZ[{ele, mu}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[1] , F[3] ] == {{0, (-1/2*I)*(Mtau*Conjugate[FR$deltaZ[{ta, ele}, {{}}, "R"]] + Mele*FR$deltaZ[{ele, ta}, {{}}, "L"])}, {0, (-1/2*I)*(Mtau*Conjugate[FR$deltaZ[{ta, ele}, {{}}, "L"]] + Mele*FR$deltaZ[{ele, ta}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{ta, ele}, {{}}, "L"]] + FR$deltaZ[{ele, ta}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{ta, ele}, {{}}, "R"]] + FR$deltaZ[{ele, ta}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] ] == {{0, (-1/2*I)*lambdah*(Mmu*Conjugate[FR$deltaZ[{mu, ele}, {{}}, "R"]] + Mele*FR$deltaZ[{ele, mu}, {{}}, "L"])}, {0, (-1/2*I)*lambdah*(Mmu*Conjugate[FR$deltaZ[{mu, ele}, {{}}, "L"]] + Mele*FR$deltaZ[{ele, mu}, {{}}, "R"])}},

C[ -F[1] , F[3] , S[1] ] == {{0, (-1/2*I)*lambdah*(Mtau*Conjugate[FR$deltaZ[{ta, ele}, {{}}, "R"]] + Mele*FR$deltaZ[{ele, ta}, {{}}, "L"])}, {0, (-1/2*I)*lambdah*(Mtau*Conjugate[FR$deltaZ[{ta, ele}, {{}}, "L"]] + Mele*FR$deltaZ[{ele, ta}, {{}}, "R"])}},

C[ -F[2] , F[1] ] == {{0, (-1/2*I)*(Mele*Conjugate[FR$deltaZ[{ele, mu}, {{}}, "R"]] + Mmu*FR$deltaZ[{mu, ele}, {{}}, "L"])}, {0, (-1/2*I)*(Mele*Conjugate[FR$deltaZ[{ele, mu}, {{}}, "L"]] + Mmu*FR$deltaZ[{mu, ele}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{ele, mu}, {{}}, "L"]] + FR$deltaZ[{mu, ele}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{ele, mu}, {{}}, "R"]] + FR$deltaZ[{mu, ele}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[2] , F[3] ] == {{0, (-1/2*I)*(Mtau*Conjugate[FR$deltaZ[{ta, mu}, {{}}, "R"]] + Mmu*FR$deltaZ[{mu, ta}, {{}}, "L"])}, {0, (-1/2*I)*(Mtau*Conjugate[FR$deltaZ[{ta, mu}, {{}}, "L"]] + Mmu*FR$deltaZ[{mu, ta}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{ta, mu}, {{}}, "L"]] + FR$deltaZ[{mu, ta}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{ta, mu}, {{}}, "R"]] + FR$deltaZ[{mu, ta}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] ] == {{0, (-1/2*I)*lambdah*(Mele*Conjugate[FR$deltaZ[{ele, mu}, {{}}, "R"]] + Mmu*FR$deltaZ[{mu, ele}, {{}}, "L"])}, {0, (-1/2*I)*lambdah*(Mele*Conjugate[FR$deltaZ[{ele, mu}, {{}}, "L"]] + Mmu*FR$deltaZ[{mu, ele}, {{}}, "R"])}},

C[ -F[2] , F[3] , S[1] ] == {{0, (-1/2*I)*lambdah*(Mtau*Conjugate[FR$deltaZ[{ta, mu}, {{}}, "R"]] + Mmu*FR$deltaZ[{mu, ta}, {{}}, "L"])}, {0, (-1/2*I)*lambdah*(Mtau*Conjugate[FR$deltaZ[{ta, mu}, {{}}, "L"]] + Mmu*FR$deltaZ[{mu, ta}, {{}}, "R"])}},

C[ -F[3] , F[1] ] == {{0, (-1/2*I)*(Mele*Conjugate[FR$deltaZ[{ele, ta}, {{}}, "R"]] + Mtau*FR$deltaZ[{ta, ele}, {{}}, "L"])}, {0, (-1/2*I)*(Mele*Conjugate[FR$deltaZ[{ele, ta}, {{}}, "L"]] + Mtau*FR$deltaZ[{ta, ele}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{ele, ta}, {{}}, "L"]] + FR$deltaZ[{ta, ele}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{ele, ta}, {{}}, "R"]] + FR$deltaZ[{ta, ele}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[3] , F[2] ] == {{0, (-1/2*I)*(Mmu*Conjugate[FR$deltaZ[{mu, ta}, {{}}, "R"]] + Mtau*FR$deltaZ[{ta, mu}, {{}}, "L"])}, {0, (-1/2*I)*(Mmu*Conjugate[FR$deltaZ[{mu, ta}, {{}}, "L"]] + Mtau*FR$deltaZ[{ta, mu}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{mu, ta}, {{}}, "L"]] + FR$deltaZ[{ta, mu}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{mu, ta}, {{}}, "R"]] + FR$deltaZ[{ta, mu}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[3] , F[1] , S[1] ] == {{0, (-1/2*I)*lambdah*(Mele*Conjugate[FR$deltaZ[{ele, ta}, {{}}, "R"]] + Mtau*FR$deltaZ[{ta, ele}, {{}}, "L"])}, {0, (-1/2*I)*lambdah*(Mele*Conjugate[FR$deltaZ[{ele, ta}, {{}}, "L"]] + Mtau*FR$deltaZ[{ta, ele}, {{}}, "R"])}},

C[ -F[3] , F[2] , S[1] ] == {{0, (-1/2*I)*lambdah*(Mmu*Conjugate[FR$deltaZ[{mu, ta}, {{}}, "R"]] + Mtau*FR$deltaZ[{ta, mu}, {{}}, "L"])}, {0, (-1/2*I)*lambdah*(Mmu*Conjugate[FR$deltaZ[{mu, ta}, {{}}, "L"]] + Mtau*FR$deltaZ[{ta, mu}, {{}}, "R"])}},

C[ -F[1] , F[2] , V[1] ] == {{0, (I/2)*EL*(Conjugate[FR$deltaZ[{mu, ele}, {{}}, "L"]] + FR$deltaZ[{ele, mu}, {{}}, "L"])}, {0, (I/2)*EL*(Conjugate[FR$deltaZ[{mu, ele}, {{}}, "R"]] + FR$deltaZ[{ele, mu}, {{}}, "R"])}},

C[ -F[1] , F[3] , V[1] ] == {{0, (I/2)*EL*(Conjugate[FR$deltaZ[{ta, ele}, {{}}, "L"]] + FR$deltaZ[{ele, ta}, {{}}, "L"])}, {0, (I/2)*EL*(Conjugate[FR$deltaZ[{ta, ele}, {{}}, "R"]] + FR$deltaZ[{ele, ta}, {{}}, "R"])}},

C[ -F[2] , F[1] , V[1] ] == {{0, (I/2)*EL*(Conjugate[FR$deltaZ[{ele, mu}, {{}}, "L"]] + FR$deltaZ[{mu, ele}, {{}}, "L"])}, {0, (I/2)*EL*(Conjugate[FR$deltaZ[{ele, mu}, {{}}, "R"]] + FR$deltaZ[{mu, ele}, {{}}, "R"])}},

C[ -F[2] , F[3] , V[1] ] == {{0, (I/2)*EL*(Conjugate[FR$deltaZ[{ta, mu}, {{}}, "L"]] + FR$deltaZ[{mu, ta}, {{}}, "L"])}, {0, (I/2)*EL*(Conjugate[FR$deltaZ[{ta, mu}, {{}}, "R"]] + FR$deltaZ[{mu, ta}, {{}}, "R"])}},

C[ -F[3] , F[1] , V[1] ] == {{0, (I/2)*EL*(Conjugate[FR$deltaZ[{ele, ta}, {{}}, "L"]] + FR$deltaZ[{ta, ele}, {{}}, "L"])}, {0, (I/2)*EL*(Conjugate[FR$deltaZ[{ele, ta}, {{}}, "R"]] + FR$deltaZ[{ta, ele}, {{}}, "R"])}},

C[ -F[3] , F[2] , V[1] ] == {{0, (I/2)*EL*(Conjugate[FR$deltaZ[{mu, ta}, {{}}, "L"]] + FR$deltaZ[{ta, mu}, {{}}, "L"])}, {0, (I/2)*EL*(Conjugate[FR$deltaZ[{mu, ta}, {{}}, "R"]] + FR$deltaZ[{ta, mu}, {{}}, "R"])}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc6 -> -(lambdah*Mele),
     gc8 -> -(lambdah*Mmu),
     gc10 -> -(lambdah*Mtau),
     gc11 -> EL,
     gc12 -> EL,
     gc13 -> EL};

