(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Two Fermions",
  Authors -> {"S. Song"},
  Version -> "1.0.0",
  Date -> "02. 07. 2024",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> False,
    PropagatorLabel -> "Phi",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mPhi,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    PropagatorLabel -> "Psi1",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mPsi1,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    PropagatorLabel -> "Psi2",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mPsi2,
    Indices -> {} }
}


(*        Definitions       *)


mPhi[ ___ ] := mPhi;
mPsi1[ ___ ] := mPsi1;
mPsi2[ ___ ] := mPsi2;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , -S[1] ] == {{0, (-I)*mPhi*(2*FR$delta[{mPhi}, {}] + mPhi*FR$deltaZ[{Phi, Phi}, {{}}])}, {0, (-I)*FR$deltaZ[{Phi, Phi}, {{}}]}},

C[ S[1] , S[1] , -S[1] , -S[1] ] == {{(-I)*lambda4, (-I)*(FR$delta[{lambda4}, {}] + 2*lambda4*FR$deltaZ[{Phi, Phi}, {{}}])}},

C[ -F[1] , F[1] ] == {{0, (-1/2*I)*(2*FR$delta[{mPsi1}, {}] + mPsi1*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + mPsi1*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{mPsi1}, {}] + mPsi1*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + mPsi1*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])}, {0, I*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"]}, {0, I*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[1] , F[1] , S[1] ] == {{-(gc4*(Y1i - I*Y1r)), (2*FR$delta[{Y1i}, {}] - (2*I)*FR$delta[{Y1r}, {}] + Y1i*FR$deltaZ[{Phi, Phi}, {{}}] - I*Y1r*FR$deltaZ[{Phi, Phi}, {{}}] + Y1i*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] - I*Y1r*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + Y1i*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"] - I*Y1r*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])/2}, {-(gc4*(Y1i - I*Y1r)), (2*FR$delta[{Y1i}, {}] - (2*I)*FR$delta[{Y1r}, {}] + Y1i*FR$deltaZ[{Phi, Phi}, {{}}] - I*Y1r*FR$deltaZ[{Phi, Phi}, {{}}] + Y1i*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] - I*Y1r*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] + Y1i*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"] - I*Y1r*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])/2}},

C[ -F[1] , F[1] , -S[1] ] == {{gc5*(Y1i + I*Y1r), (-2*FR$delta[{Y1i}, {}] - (2*I)*FR$delta[{Y1r}, {}] - Y1i*FR$deltaZ[{Phi, Phi}, {{}}] - I*Y1r*FR$deltaZ[{Phi, Phi}, {{}}] - Y1i*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] - I*Y1r*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] - Y1i*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"] - I*Y1r*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])/2}, {gc5*(Y1i + I*Y1r), (-2*FR$delta[{Y1i}, {}] - (2*I)*FR$delta[{Y1r}, {}] - Y1i*FR$deltaZ[{Phi, Phi}, {{}}] - I*Y1r*FR$deltaZ[{Phi, Phi}, {{}}] - Y1i*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] - I*Y1r*FR$deltaZ[{Psi1, Psi1}, {{}}, "L"] - Y1i*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"] - I*Y1r*FR$deltaZ[{Psi1, Psi1}, {{}}, "R"])/2}},

C[ -F[2] , F[2] ] == {{0, (-1/2*I)*(2*FR$delta[{mPsi2}, {}] + mPsi2*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] + mPsi2*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{mPsi2}, {}] + mPsi2*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] + mPsi2*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])}, {0, I*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"]}, {0, I*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , S[1] ] == {{-(gc7*(Y2i - I*Y2r)), (2*FR$delta[{Y2i}, {}] - (2*I)*FR$delta[{Y2r}, {}] + Y2i*FR$deltaZ[{Phi, Phi}, {{}}] - I*Y2r*FR$deltaZ[{Phi, Phi}, {{}}] + Y2i*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] - I*Y2r*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] + Y2i*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"] - I*Y2r*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])/2}, {-(gc7*(Y2i - I*Y2r)), (2*FR$delta[{Y2i}, {}] - (2*I)*FR$delta[{Y2r}, {}] + Y2i*FR$deltaZ[{Phi, Phi}, {{}}] - I*Y2r*FR$deltaZ[{Phi, Phi}, {{}}] + Y2i*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] - I*Y2r*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] + Y2i*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"] - I*Y2r*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])/2}},

C[ -F[2] , F[2] , -S[1] ] == {{gc8*(Y2i + I*Y2r), (-2*FR$delta[{Y2i}, {}] - (2*I)*FR$delta[{Y2r}, {}] - Y2i*FR$deltaZ[{Phi, Phi}, {{}}] - I*Y2r*FR$deltaZ[{Phi, Phi}, {{}}] - Y2i*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] - I*Y2r*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] - Y2i*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"] - I*Y2r*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])/2}, {gc8*(Y2i + I*Y2r), (-2*FR$delta[{Y2i}, {}] - (2*I)*FR$delta[{Y2r}, {}] - Y2i*FR$deltaZ[{Phi, Phi}, {{}}] - I*Y2r*FR$deltaZ[{Phi, Phi}, {{}}] - Y2i*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] - I*Y2r*FR$deltaZ[{Psi2, Psi2}, {{}}, "L"] - Y2i*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"] - I*Y2r*FR$deltaZ[{Psi2, Psi2}, {{}}, "R"])/2}},

C[ -F[1] , F[2] ] == {{0, (-1/2*I)*(mPsi2*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]] + mPsi1*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"])}, {0, (-1/2*I)*(mPsi2*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]] + mPsi1*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]] + FR$deltaZ[{Psi1, Psi2}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]] + FR$deltaZ[{Psi1, Psi2}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[1] , F[2] , S[1] ] == {{0, (Y2i*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]] - I*Y2r*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]] + Y1i*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"] - I*Y1r*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"])/2}, {0, (Y2i*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]] - I*Y2r*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]] + Y1i*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"] - I*Y1r*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"])/2}},

C[ -F[1] , F[2] , -S[1] ] == {{0, (-(Y2i*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]]) - I*Y2r*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "R"]] - Y1i*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"] - I*Y1r*FR$deltaZ[{Psi1, Psi2}, {{}}, "L"])/2}, {0, (-(Y2i*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]]) - I*Y2r*Conjugate[FR$deltaZ[{Psi2, Psi1}, {{}}, "L"]] - Y1i*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"] - I*Y1r*FR$deltaZ[{Psi1, Psi2}, {{}}, "R"])/2}},

C[ -F[2] , F[1] ] == {{0, (-1/2*I)*(mPsi1*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]] + mPsi2*FR$deltaZ[{Psi2, Psi1}, {{}}, "L"])}, {0, (-1/2*I)*(mPsi1*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]] + mPsi2*FR$deltaZ[{Psi2, Psi1}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]] + FR$deltaZ[{Psi2, Psi1}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]] + FR$deltaZ[{Psi2, Psi1}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[1] ] == {{0, (Y1i*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]] - I*Y1r*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]] + Y2i*FR$deltaZ[{Psi2, Psi1}, {{}}, "L"] - I*Y2r*FR$deltaZ[{Psi2, Psi1}, {{}}, "L"])/2}, {0, (Y1i*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]] - I*Y1r*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]] + Y2i*FR$deltaZ[{Psi2, Psi1}, {{}}, "R"] - I*Y2r*FR$deltaZ[{Psi2, Psi1}, {{}}, "R"])/2}},

C[ -F[2] , F[1] , -S[1] ] == {{0, (-(Y1i*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]]) - I*Y1r*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "R"]] - Y2i*FR$deltaZ[{Psi2, Psi1}, {{}}, "L"] - I*Y2r*FR$deltaZ[{Psi2, Psi1}, {{}}, "L"])/2}, {0, (-(Y1i*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]]) - I*Y1r*Conjugate[FR$deltaZ[{Psi1, Psi2}, {{}}, "L"]] - Y2i*FR$deltaZ[{Psi2, Psi1}, {{}}, "R"] - I*Y2r*FR$deltaZ[{Psi2, Psi1}, {{}}, "R"])/2}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc4 -> -1,
     gc5 -> -1,
     gc7 -> -1,
     gc8 -> -1};

