(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Photonless Weak",
  Authors -> {"S. Song"},
  Version -> "1.0.2",
  Date -> "05. 06. 2024",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"}};

FR$ClassesTranslation={H -> S[1], Chi1 -> S[2], Chi2 -> S[3], Chi3 -> S[4], W1 -> V[1], W2 -> V[2], W3 -> V[3], c1 -> U[1], c2 -> U[2], c3 -> U[3], u -> F[1], d -> F[2]};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={S[2], S[3], S[4]};

(*     Declared indices    *)

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi1" },

S[3] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi2" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi3" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W1" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W2" },

V[3] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W3" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c1" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c2" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c3" },

F[1] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu,
    Indices -> {},
    PropagatorLabel -> "u" },

F[2] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md,
    Indices -> {},
    PropagatorLabel -> "d" }
}


(*        Definitions       *)


mh[ ___ ] := mh;
mW[ ___ ] := mW;
Mu[ ___ ] := Mu;
Md[ ___ ] := Md;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[3] , S[3] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[4] , S[4] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[4] , S[4] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[1] , S[1] ] == {{0, (-I)*mh*(2*FR$delta[{mh}, {}] + mh*FR$deltaZ[{H, H}, {{}}])}, {0, (-I)*FR$deltaZ[{H, H}, {{}}]}},

C[ S[2] , S[2] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi1, Chi1}, {{}}]}},

C[ S[3] , S[3] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi2, Chi2}, {{}}]}},

C[ S[4] , S[4] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi3, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[3] , S[3] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[4] , S[4] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lambda*vH, ((-3*I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 3*mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[2] , V[1] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*FR$deltaZ[{W1, W1}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*FR$deltaZ[{W1, W1}, {{}}])/2}},

C[ V[1] , V[1] ] == {{0, (-I)*FR$deltaZ[{W1, W1}, {{}}]}, {0, I*FR$deltaZ[{W1, W1}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W1, W1}, {{}}])}, {0, I*FR$deltaZ[{W1, W1}, {{}}]}},

C[ S[3] , V[2] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*FR$deltaZ[{W2, W2}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*FR$deltaZ[{W2, W2}, {{}}])/2}},

C[ V[2] , V[2] ] == {{0, (-I)*FR$deltaZ[{W2, W2}, {{}}]}, {0, I*FR$deltaZ[{W2, W2}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W2, W2}, {{}}])}, {0, I*FR$deltaZ[{W2, W2}, {{}}]}},

C[ S[4] , V[3] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*FR$deltaZ[{W3, W3}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*FR$deltaZ[{W3, W3}, {{}}])/2}},

C[ V[3] , V[3] ] == {{0, (-I)*FR$deltaZ[{W3, W3}, {{}}]}, {0, I*FR$deltaZ[{W3, W3}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W3, W3}, {{}}])}, {0, I*FR$deltaZ[{W3, W3}, {{}}]}},

C[ -U[1] , U[1] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[1] , U[1] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[4] , -U[1] , U[2] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/mW}},

C[ -U[1] , U[2] , V[3] ] == {{gc28, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc28, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[3] , -U[1] , U[3] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/mW}},

C[ -U[1] , U[3] , V[2] ] == {{gc30, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {gc30, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {0, 0}},

C[ S[4] , -U[2] , U[1] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/mW}},

C[ -U[2] , U[1] , V[3] ] == {{gc32, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc32, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {0, 0}},

C[ -U[2] , U[2] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[2] , -U[2] , U[3] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/mW}},

C[ -U[2] , U[3] , V[1] ] == {{gc36, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(2*mW*vH)}, {gc36, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/mW}},

C[ -U[3] , U[1] , V[2] ] == {{gc38, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(2*mW*vH)}, {gc38, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[2] , -U[3] , U[2] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/mW}},

C[ -U[3] , U[2] , V[1] ] == {{gc40, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {gc40, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {0, 0}},

C[ -U[3] , U[3] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[3] , U[3] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[2] , S[2] , S[2] , S[3] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[3] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[4] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[3] , V[1] ] == {{0, (mW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/2}},

C[ S[3] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, Chi2}, {{}}]}},

C[ S[3] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[2] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[4] , V[1] ] == {{0, (mW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/2}},

C[ S[4] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[2] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi1, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi1, H}, {{}}] + 3*FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[1] , V[1] ] == {{0, (mW*FR$deltaZ[{Chi1, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi1, H}, {{}}])/2}},

C[ S[1] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, H}, {{}}]}},

C[ S[1] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, H}, {{}}]}},

C[ S[2] , V[2] ] == {{0, (mW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/2}},

C[ S[2] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, Chi1}, {{}}]}},

C[ S[2] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, Chi1}, {{}}]}},

C[ S[2] , S[2] , S[3] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[3] , S[3] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[4] , V[2] ] == {{0, (mW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}]))/2}},

C[ S[4] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[3] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[3] , S[3] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi2, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi2}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi2, H}, {{}}] + 3*FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[1] , V[2] ] == {{0, (mW*FR$deltaZ[{Chi2, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi2, H}, {{}}])/2}},

C[ S[1] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, H}, {{}}]}},

C[ S[1] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, H}, {{}}]}},

C[ S[2] , V[3] ] == {{0, (mW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{W1, W3}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{W1, W3}, {{}}]))/2}},

C[ S[2] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, Chi1}, {{}}]}},

C[ S[2] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, Chi1}, {{}}]}},

C[ S[3] , V[3] ] == {{0, (mW*(FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/2}},

C[ S[3] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, Chi2}, {{}}]}},

C[ S[3] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[3] , S[3] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[4] , S[4] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi3, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi3}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi3, H}, {{}}] + 3*FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[1] , V[3] ] == {{0, (mW*FR$deltaZ[{Chi3, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi3, H}, {{}}])/2}},

C[ S[1] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, H}, {{}}]}},

C[ S[1] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, H}, {{}}]}},

C[ S[2] , S[2] , S[2] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[3] , S[3] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[4] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[2] , S[3] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , S[3] , S[3] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , S[4] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[3] , S[3] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[2] ] == {{0, (-1/2*I)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ -U[2] , U[3] , V[2] ] == {{0, (gW*FR$deltaZ[{W1, W2}, {{}}])/2}, {0, (gW*FR$deltaZ[{W1, W2}, {{}}])/2}, {0, 0}},

C[ -U[3] , U[2] , V[2] ] == {{0, -1/2*(gW*FR$deltaZ[{W1, W2}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W1, W2}, {{}}])}, {0, 0}},

C[ V[1] , V[3] ] == {{0, (-1/2*I)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ -U[2] , U[3] , V[3] ] == {{0, (gW*FR$deltaZ[{W1, W3}, {{}}])/2}, {0, (gW*FR$deltaZ[{W1, W3}, {{}}])/2}, {0, 0}},

C[ -U[3] , U[2] , V[3] ] == {{0, -1/2*(gW*FR$deltaZ[{W1, W3}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W1, W3}, {{}}])}, {0, 0}},

C[ -U[1] , U[3] , V[1] ] == {{0, -1/2*(gW*FR$deltaZ[{W2, W1}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W2, W1}, {{}}])}, {0, 0}},

C[ -U[3] , U[1] , V[1] ] == {{0, (gW*FR$deltaZ[{W2, W1}, {{}}])/2}, {0, (gW*FR$deltaZ[{W2, W1}, {{}}])/2}, {0, 0}},

C[ V[2] , V[3] ] == {{0, (-1/2*I)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ -U[1] , U[3] , V[3] ] == {{0, -1/2*(gW*FR$deltaZ[{W2, W3}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W2, W3}, {{}}])}, {0, 0}},

C[ -U[3] , U[1] , V[3] ] == {{0, (gW*FR$deltaZ[{W2, W3}, {{}}])/2}, {0, (gW*FR$deltaZ[{W2, W3}, {{}}])/2}, {0, 0}},

C[ -U[1] , U[2] , V[1] ] == {{0, (gW*FR$deltaZ[{W3, W1}, {{}}])/2}, {0, (gW*FR$deltaZ[{W3, W1}, {{}}])/2}, {0, 0}},

C[ -U[2] , U[1] , V[1] ] == {{0, -1/2*(gW*FR$deltaZ[{W3, W1}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W3, W1}, {{}}])}, {0, 0}},

C[ -U[1] , U[2] , V[2] ] == {{0, (gW*FR$deltaZ[{W3, W2}, {{}}])/2}, {0, (gW*FR$deltaZ[{W3, W2}, {{}}])/2}, {0, 0}},

C[ -U[2] , U[1] , V[2] ] == {{0, -1/2*(gW*FR$deltaZ[{W3, W2}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W3, W2}, {{}}])}, {0, 0}},

C[ -F[1] , F[2] , S[2] ] == {{gc139L, (yu*(2*vH*FR$delta[{Mu}, {}] - 2*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] - I*Mu*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Mu*vH*FR$deltaZ[{d, d}, {{}}, "L"] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(2*Sqrt[2]*Mu*vH)}, {gc139R, -1/2*(yd*(2*vH*FR$delta[{Md}, {}] - 2*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] - I*Md*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Md*vH*FR$deltaZ[{d, d}, {{}}, "R"] + Md*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(Sqrt[2]*Md*vH)}},

C[ -F[1] , F[2] , S[3] ] == {{I*gc140L, (yu*((-2*I)*vH*FR$delta[{Mu}, {}] + (2*I)*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] - I*Mu*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] - I*Mu*vH*FR$deltaZ[{d, d}, {{}}, "L"] - I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(2*Sqrt[2]*Mu*vH)}, {I*gc140R, -1/2*(yd*((-2*I)*vH*FR$delta[{Md}, {}] + (2*I)*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] - I*Md*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] - I*Md*vH*FR$deltaZ[{d, d}, {{}}, "R"] - I*Md*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(Sqrt[2]*Md*vH)}},

C[ -F[1] , F[2] , S[4] ] == {{0, -1/2*(yd*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] - yu*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yu*FR$deltaZ[{Chi2, Chi3}, {{}}] - yu*FR$deltaZ[{u, d}, {{}}, "L"])/Sqrt[2]}, {0, (yd*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] - yd*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yd*FR$deltaZ[{Chi2, Chi3}, {{}}] - yu*FR$deltaZ[{u, d}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[1] , F[2] , S[1] ] == {{0, ((-I)*yd*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + yu*FR$deltaZ[{Chi1, H}, {{}}] - I*yu*FR$deltaZ[{Chi2, H}, {{}}] - I*yu*FR$deltaZ[{u, d}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yd*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] - I*yd*FR$deltaZ[{Chi1, H}, {{}}] - yd*FR$deltaZ[{Chi2, H}, {{}}] + yu*FR$deltaZ[{u, d}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[1] , F[1] ] == {{0, (-1/2*I)*(2*FR$delta[{Mu}, {}] + Mu*FR$deltaZ[{u, u}, {{}}, "L"] + Mu*FR$deltaZ[{u, u}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Mu}, {}] + Mu*FR$deltaZ[{u, u}, {{}}, "L"] + Mu*FR$deltaZ[{u, u}, {{}}, "R"])}, {0, I*FR$deltaZ[{u, u}, {{}}, "L"]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[1] , F[1] , S[4] ] == {{gc144L, (yu*(2*vH*FR$delta[{Mu}, {}] - 2*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] - I*Mu*vH*FR$deltaZ[{H, Chi3}, {{}}] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "L"] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(2*Sqrt[2]*Mu*vH)}, {gc144R, -1/2*(yu*(2*vH*FR$delta[{Mu}, {}] - 2*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + I*Mu*vH*FR$deltaZ[{H, Chi3}, {{}}] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "L"] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(Sqrt[2]*Mu*vH)}},

C[ -F[1] , F[1] , S[1] ] == {{I*gc145, (yu*((-2*I)*vH*FR$delta[{Mu}, {}] + (2*I)*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi3, H}, {{}}] - I*Mu*vH*FR$deltaZ[{H, H}, {{}}] - I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "L"] - I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(2*Sqrt[2]*Mu*vH)}, {I*gc145, -1/2*(yu*((2*I)*vH*FR$delta[{Mu}, {}] - (2*I)*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi3, H}, {{}}] + I*Mu*vH*FR$deltaZ[{H, H}, {{}}] + I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "L"] + I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(Sqrt[2]*Mu*vH)}},

C[ -F[1] , F[1] , S[2] ] == {{0, (yd*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + yu*FR$deltaZ[{Chi3, Chi1}, {{}}] - I*yu*FR$deltaZ[{H, Chi1}, {{}}] + yu*FR$deltaZ[{d, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + yu*FR$deltaZ[{Chi3, Chi1}, {{}}] + I*yu*FR$deltaZ[{H, Chi1}, {{}}] + yd*FR$deltaZ[{d, u}, {{}}, "R"])/Sqrt[2]}},

C[ -F[1] , F[1] , S[3] ] == {{0, (I*yd*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + yu*FR$deltaZ[{Chi3, Chi2}, {{}}] - I*yu*FR$deltaZ[{H, Chi2}, {{}}] - I*yu*FR$deltaZ[{d, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yu*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] - I*yu*FR$deltaZ[{Chi3, Chi2}, {{}}] + yu*FR$deltaZ[{H, Chi2}, {{}}] - yd*FR$deltaZ[{d, u}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[1] , F[2] ] == {{0, (-1/2*I)*(Md*Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + Mu*FR$deltaZ[{u, d}, {{}}, "L"])}, {0, (-1/2*I)*(Md*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + Mu*FR$deltaZ[{u, d}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + FR$deltaZ[{u, d}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, u}, {{}}, "R"]] + FR$deltaZ[{u, d}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ -F[2] , F[1] , S[2] ] == {{gc149L, (yd*(2*vH*FR$delta[{Md}, {}] - 2*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + I*Md*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Md*vH*FR$deltaZ[{d, d}, {{}}, "R"] + Md*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(2*Sqrt[2]*Md*vH)}, {gc149R, -1/2*(yu*(2*vH*FR$delta[{Mu}, {}] - 2*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + I*Mu*vH*FR$deltaZ[{Chi2, Chi1}, {{}}] + Mu*vH*FR$deltaZ[{d, d}, {{}}, "L"] + Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(Sqrt[2]*Mu*vH)}},

C[ -F[2] , F[1] , S[3] ] == {{I*gc150L, (yd*((2*I)*vH*FR$delta[{Md}, {}] - (2*I)*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] + I*Md*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + I*Md*vH*FR$deltaZ[{d, d}, {{}}, "R"] + I*Md*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(2*Sqrt[2]*Md*vH)}, {I*gc150R, -1/2*(yu*((2*I)*vH*FR$delta[{Mu}, {}] - (2*I)*Mu*FR$delta[{vH}, {}] + Mu*vH*FR$deltaZ[{Chi1, Chi2}, {{}}] + I*Mu*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + I*Mu*vH*FR$deltaZ[{d, d}, {{}}, "L"] + I*Mu*vH*FR$deltaZ[{u, u}, {{}}, "R"]))/(Sqrt[2]*Mu*vH)}},

C[ -F[2] , F[1] , S[4] ] == {{0, (yu*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] + yd*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yd*FR$deltaZ[{Chi2, Chi3}, {{}}] - yd*FR$deltaZ[{d, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yu*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + yu*FR$deltaZ[{Chi1, Chi3}, {{}}] + I*yu*FR$deltaZ[{Chi2, Chi3}, {{}}] - yd*FR$deltaZ[{d, u}, {{}}, "R"])/Sqrt[2]}},

C[ -F[2] , F[1] , S[1] ] == {{0, ((-I)*yu*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] + yd*FR$deltaZ[{Chi1, H}, {{}}] + I*yd*FR$deltaZ[{Chi2, H}, {{}}] - I*yd*FR$deltaZ[{d, u}, {{}}, "L"])/(2*Sqrt[2])}, {0, ((-1/2*I)*(yu*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] - I*yu*FR$deltaZ[{Chi1, H}, {{}}] + yu*FR$deltaZ[{Chi2, H}, {{}}] + yd*FR$deltaZ[{d, u}, {{}}, "R"]))/Sqrt[2]}},

C[ -F[2] , F[2] ] == {{0, (-1/2*I)*(2*FR$delta[{Md}, {}] + Md*FR$deltaZ[{d, d}, {{}}, "L"] + Md*FR$deltaZ[{d, d}, {{}}, "R"])}, {0, (-1/2*I)*(2*FR$delta[{Md}, {}] + Md*FR$deltaZ[{d, d}, {{}}, "L"] + Md*FR$deltaZ[{d, d}, {{}}, "R"])}, {0, I*FR$deltaZ[{d, d}, {{}}, "L"]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]}, {0, 0}, {0, 0}},

C[ -F[2] , F[2] , S[4] ] == {{gc154L, -1/2*(yd*(2*vH*FR$delta[{Md}, {}] - 2*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + I*Md*vH*FR$deltaZ[{H, Chi3}, {{}}] + Md*vH*FR$deltaZ[{d, d}, {{}}, "L"] + Md*vH*FR$deltaZ[{d, d}, {{}}, "R"]))/(Sqrt[2]*Md*vH)}, {gc154R, (yd*(2*vH*FR$delta[{Md}, {}] - 2*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] - I*Md*vH*FR$deltaZ[{H, Chi3}, {{}}] + Md*vH*FR$deltaZ[{d, d}, {{}}, "L"] + Md*vH*FR$deltaZ[{d, d}, {{}}, "R"]))/(2*Sqrt[2]*Md*vH)}},

C[ -F[2] , F[2] , S[1] ] == {{I*gc155, -1/2*(yd*((2*I)*vH*FR$delta[{Md}, {}] - (2*I)*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi3, H}, {{}}] + I*Md*vH*FR$deltaZ[{H, H}, {{}}] + I*Md*vH*FR$deltaZ[{d, d}, {{}}, "L"] + I*Md*vH*FR$deltaZ[{d, d}, {{}}, "R"]))/(Sqrt[2]*Md*vH)}, {I*gc155, (yd*((-2*I)*vH*FR$delta[{Md}, {}] + (2*I)*Md*FR$delta[{vH}, {}] + Md*vH*FR$deltaZ[{Chi3, H}, {{}}] - I*Md*vH*FR$deltaZ[{H, H}, {{}}] - I*Md*vH*FR$deltaZ[{d, d}, {{}}, "L"] - I*Md*vH*FR$deltaZ[{d, d}, {{}}, "R"]))/(2*Sqrt[2]*Md*vH)}},

C[ -F[2] , F[2] , S[2] ] == {{0, (yu*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] - yd*FR$deltaZ[{Chi3, Chi1}, {{}}] - I*yd*FR$deltaZ[{H, Chi1}, {{}}] + yd*FR$deltaZ[{u, d}, {{}}, "L"])/(2*Sqrt[2])}, {0, -1/2*(yd*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] - yd*FR$deltaZ[{Chi3, Chi1}, {{}}] + I*yd*FR$deltaZ[{H, Chi1}, {{}}] + yu*FR$deltaZ[{u, d}, {{}}, "R"])/Sqrt[2]}},

C[ -F[2] , F[2] , S[3] ] == {{0, ((-1/2*I)*(yu*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] - I*yd*FR$deltaZ[{Chi3, Chi2}, {{}}] + yd*FR$deltaZ[{H, Chi2}, {{}}] - yd*FR$deltaZ[{u, d}, {{}}, "L"]))/Sqrt[2]}, {0, (I*yd*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + yd*FR$deltaZ[{Chi3, Chi2}, {{}}] - I*yd*FR$deltaZ[{H, Chi2}, {{}}] - I*yu*FR$deltaZ[{u, d}, {{}}, "R"])/(2*Sqrt[2])}},

C[ -F[2] , F[1] ] == {{0, (-1/2*I)*(Mu*Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] + Md*FR$deltaZ[{d, u}, {{}}, "L"])}, {0, (-1/2*I)*(Mu*Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + Md*FR$deltaZ[{d, u}, {{}}, "R"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + FR$deltaZ[{d, u}, {{}}, "L"])}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, d}, {{}}, "R"]] + FR$deltaZ[{d, u}, {{}}, "R"])}, {0, 0}, {0, 0}},

C[ S[2] , S[1] , V[1] ] == {{-gc159, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(4*mW*vH)}, {gc159, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[1] ] == {{-gc160, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {gc160, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(4*mW*vH)}},

C[ S[3] , S[1] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] - FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] - FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))}},

C[ S[4] , S[1] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))}},

C[ S[2] , S[4] , V[1] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] - FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W2, W1}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] - FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W2, W1}, {{}}]))/4}},

C[ S[2] , S[3] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W3, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W3, W1}, {{}}]))}},

C[ S[2] , S[2] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[1] , V[1] , V[1] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/mW}},

C[ S[2] , S[3] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[2] , S[4] , V[2] ] == {{-gc179, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(4*mW*vH)}, {gc179, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[1] , V[2] ] == {{-gc180, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(4*mW*vH)}, {gc180, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W1, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W1, W2}, {{}}]))}},

C[ S[4] , S[1] , V[2] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi1, H}, {{}}] - FR$deltaZ[{Chi2, Chi3}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi1, H}, {{}}] - FR$deltaZ[{Chi2, Chi3}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))/4}},

C[ S[2] , S[1] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))}},

C[ S[2] , S[3] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi3, Chi2}, {{}}] - FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi3, Chi2}, {{}}] - FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))}},

C[ S[2] , S[2] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[3] , S[3] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[4] , S[4] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[1] , V[1] , V[2] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ V[1] , V[2] , V[3] ] == {{-gc190, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc190, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc190, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {-gc190, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {-gc190, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc190, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[1] , V[2] , V[2] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/mW}},

C[ S[2] , S[3] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[1] , V[2] , V[2] ] == {{(-I)*gc205, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {(-I)*gc205, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {(2*I)*gc205, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[2] , S[3] , V[3] ] == {{-gc206, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc206, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(4*mW*vH)}},

C[ S[4] , S[1] , V[3] ] == {{-gc207, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(4*mW*vH)}, {gc207, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[3] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] - FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] - FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))}},

C[ S[3] , S[1] , V[3] ] == {{0, (gW*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))}},

C[ S[2] , S[4] , V[3] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W2, W3}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W2, W3}, {{}}]))/4}},

C[ S[2] , S[1] , V[3] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, H}, {{}}] - FR$deltaZ[{Chi3, Chi1}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, H}, {{}}] - FR$deltaZ[{Chi3, Chi1}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))/4}},

C[ S[2] , S[2] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[3] , S[3] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[4] , S[4] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[1] , S[1] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[1] , V[1] , V[3] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[2] , S[2] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[3] , S[3] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[4] , S[4] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[1] , S[1] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[1] , V[2] , V[3] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ V[1] , V[1] , V[2] , V[3] ] == {{0, (I/2)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (-I)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ V[1] , V[2] , V[2] , V[3] ] == {{0, (-I)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[2] , S[2] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[1] , V[3] , V[3] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/mW}},

C[ S[2] , S[3] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[1] , V[3] , V[3] ] == {{(-I)*gc238, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(-I)*gc238, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(2*I)*gc238, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ V[1] , V[2] , V[3] , V[3] ] == {{0, (I/2)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (-I)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ V[2] , V[2] , V[3] , V[3] ] == {{(-I)*gc240, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(-I)*gc240, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(2*I)*gc240, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ -F[1] , F[2] , V[1] ] == {{I*gc241, (gW*((2*I)*vH*FR$delta[{mW}, {}] - (2*I)*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W1}, {{}}] + I*mW*vH*FR$deltaZ[{d, d}, {{}}, "L"] + I*mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[1] , F[2] , V[2] ] == {{gc242, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W2}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{d, d}, {{}}, "L"] + mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[1] , F[2] , V[3] ] == {{0, (gW*((-I)*Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + I*FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W2, W3}, {{}}] + I*FR$deltaZ[{u, d}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[1] , F[1] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] + FR$deltaZ[{W3, W1}, {{}}] + FR$deltaZ[{d, u}, {{}}, "L"])}, {0, 0}},

C[ -F[2] , F[1] , V[1] ] == {{I*gc245, ((I/4)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + I*mW*vH*FR$deltaZ[{W2, W1}, {{}}] + mW*vH*FR$deltaZ[{d, d}, {{}}, "L"] + mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(mW*vH)}, {0, 0}},

C[ -F[2] , F[1] , V[2] ] == {{gc246, (gW*(-2*vH*FR$delta[{mW}, {}] + 2*mW*FR$delta[{vH}, {}] + I*mW*vH*FR$deltaZ[{W1, W2}, {{}}] - mW*vH*FR$deltaZ[{W2, W2}, {{}}] - mW*vH*FR$deltaZ[{d, d}, {{}}, "L"] - mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(4*mW*vH)}, {0, 0}},

C[ -F[2] , F[1] , V[3] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] + FR$deltaZ[{W1, W3}, {{}}] + I*FR$deltaZ[{W2, W3}, {{}}] - FR$deltaZ[{d, u}, {{}}, "L"])}, {0, 0}},

C[ -F[2] , F[2] , V[1] ] == {{0, (I/4)*gW*(Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] - FR$deltaZ[{W3, W1}, {{}}] + FR$deltaZ[{u, d}, {{}}, "L"])}, {0, 0}},

C[ -F[1] , F[1] , V[2] ] == {{0, -1/4*(gW*(Conjugate[FR$deltaZ[{d, u}, {{}}, "L"]] - I*FR$deltaZ[{W3, W2}, {{}}] - FR$deltaZ[{d, u}, {{}}, "L"]))}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{0, (gW*(Conjugate[FR$deltaZ[{u, d}, {{}}, "L"]] - I*FR$deltaZ[{W3, W2}, {{}}] - FR$deltaZ[{u, d}, {{}}, "L"]))/4}, {0, 0}},

C[ -F[1] , F[1] , V[3] ] == {{I*gc251, ((I/4)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}] + 2*mW*vH*FR$deltaZ[{u, u}, {{}}, "L"]))/(mW*vH)}, {0, 0}},

C[ -F[2] , F[2] , V[3] ] == {{I*gc252, ((-1/4*I)*gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}] + 2*mW*vH*FR$deltaZ[{d, d}, {{}}, "L"]))/(mW*vH)}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc28 -> gW,
     gc30 -> -gW,
     gc32 -> -gW,
     gc36 -> gW,
     gc38 -> gW,
     gc40 -> -gW,
     gc139L -> yu/Sqrt[2],
     gc139R -> -(yd/Sqrt[2]),
     gc140L -> -(yu/Sqrt[2]),
     gc140R -> yd/Sqrt[2],
     gc144L -> yu/Sqrt[2],
     gc144R -> -(yu/Sqrt[2]),
     gc145 -> -(yu/Sqrt[2]),
     gc149L -> yd/Sqrt[2],
     gc149R -> -(yu/Sqrt[2]),
     gc150L -> yd/Sqrt[2],
     gc150R -> -(yu/Sqrt[2]),
     gc154L -> -(yd/Sqrt[2]),
     gc154R -> yd/Sqrt[2],
     gc155 -> -(yd/Sqrt[2]),
     gc159 -> -1/2*gW,
     gc160 -> gW/2,
     gc179 -> -1/2*gW,
     gc180 -> -1/2*gW,
     gc190 -> -gW,
     gc205 -> -gW^2,
     gc206 -> gW/2,
     gc207 -> -1/2*gW,
     gc238 -> -gW^2,
     gc240 -> -gW^2,
     gc241 -> gW/2,
     gc242 -> gW/2,
     gc245 -> gW/2,
     gc246 -> -1/2*gW,
     gc251 -> gW/2,
     gc252 -> -1/2*gW};

