(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Photonless Weak gaugeonly",
  Authors -> {"S. Song"},
  Version -> "1.0.3",
  Date -> "06. 06. 2024",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"}};

FR$ClassesTranslation={H -> S[1], Chi1 -> S[2], Chi2 -> S[3], Chi3 -> S[4], W1 -> V[1], W2 -> V[2], W3 -> V[3], c1 -> U[1], c2 -> U[2], c3 -> U[3]};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={S[2], S[3], S[4]};

(*     Declared indices    *)

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi1" },

S[3] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi2" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "Chi3" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W1" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W2" },

V[3] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "W3" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c1" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c2" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mW,
    Indices -> {},
    PropagatorLabel -> "c3" }
}


(*        Definitions       *)


mh[ ___ ] := mh;
mW[ ___ ] := mW;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[3] , S[3] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[4] , S[4] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/(mh*vH)}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[3] , S[3] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[4] , S[4] , S[1] , S[1] ] == {{(-2*I)*lambda, ((-2*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lambda, ((-6*I)*lambda*(2*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{H, H}, {{}}]))/(mh*vH)}},

C[ S[1] , S[1] ] == {{0, (-I)*mh*(2*FR$delta[{mh}, {}] + mh*FR$deltaZ[{H, H}, {{}}])}, {0, (-I)*FR$deltaZ[{H, H}, {{}}]}},

C[ S[2] , S[2] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi1, Chi1}, {{}}]}},

C[ S[3] , S[3] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi2, Chi2}, {{}}]}},

C[ S[4] , S[4] ] == {{0, (-I)*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}])}, {0, (-I)*FR$deltaZ[{Chi3, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[3] , S[3] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[4] , S[4] , S[1] ] == {{(-2*I)*lambda*vH, ((-I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 2*mh*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lambda*vH, ((-3*I)*lambda*(4*vH*FR$delta[{mh}, {}] - 2*mh*FR$delta[{vH}, {}] + 3*mh*vH*FR$deltaZ[{H, H}, {{}}]))/mh}},

C[ S[2] , V[1] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*FR$deltaZ[{W1, W1}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*FR$deltaZ[{W1, W1}, {{}}])/2}},

C[ V[1] , V[1] ] == {{0, (-I)*FR$deltaZ[{W1, W1}, {{}}]}, {0, I*FR$deltaZ[{W1, W1}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W1, W1}, {{}}])}, {0, I*FR$deltaZ[{W1, W1}, {{}}]}},

C[ S[3] , V[2] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*FR$deltaZ[{W2, W2}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*FR$deltaZ[{W2, W2}, {{}}])/2}},

C[ V[2] , V[2] ] == {{0, (-I)*FR$deltaZ[{W2, W2}, {{}}]}, {0, I*FR$deltaZ[{W2, W2}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W2, W2}, {{}}])}, {0, I*FR$deltaZ[{W2, W2}, {{}}]}},

C[ S[4] , V[3] ] == {{0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*FR$deltaZ[{W3, W3}, {{}}])/2}, {0, (2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*FR$deltaZ[{W3, W3}, {{}}])/2}},

C[ V[3] , V[3] ] == {{0, (-I)*FR$deltaZ[{W3, W3}, {{}}]}, {0, I*FR$deltaZ[{W3, W3}, {{}}]}, {0, I*mW*(2*FR$delta[{mW}, {}] + mW*FR$deltaZ[{W3, W3}, {{}}])}, {0, I*FR$deltaZ[{W3, W3}, {{}}]}},

C[ -U[1] , U[1] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[1] , U[1] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[4] , -U[1] , U[2] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/mW}},

C[ -U[1] , U[2] , V[3] ] == {{gc28, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc28, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[3] , -U[1] , U[3] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/mW}},

C[ -U[1] , U[3] , V[2] ] == {{gc30, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {gc30, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {0, 0}},

C[ S[4] , -U[2] , U[1] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}]))/mW}},

C[ -U[2] , U[1] , V[3] ] == {{gc32, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc32, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {0, 0}},

C[ -U[2] , U[2] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[2] , -U[2] , U[3] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/mW}},

C[ -U[2] , U[3] , V[1] ] == {{gc36, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(2*mW*vH)}, {gc36, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}]))/mW}},

C[ -U[3] , U[1] , V[2] ] == {{gc38, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(2*mW*vH)}, {gc38, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(2*mW*vH)}, {0, 0}},

C[ S[2] , -U[3] , U[2] ] == {{(I/4)*gW^2*vH, ((I/8)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}]))/mW}},

C[ -U[3] , U[2] , V[1] ] == {{gc40, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {gc40, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {0, 0}},

C[ -U[3] , U[3] ] == {{0, (-2*I)*mW*FR$delta[{mW}, {}]}, {0, 0}, {0, 0}},

C[ S[1] , -U[3] , U[3] ] == {{(-1/4*I)*gW^2*vH, ((-1/8*I)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}]))/mW}},

C[ S[2] , S[2] , S[2] , S[3] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[3] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[4] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[3] , V[1] ] == {{0, (mW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/2}},

C[ S[3] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, Chi2}, {{}}]}},

C[ S[3] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[2] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[4] , V[1] ] == {{0, (mW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/2}},

C[ S[4] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[2] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[3] , S[3] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[4] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi1, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi1}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[2] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi1, H}, {{}}] + 3*FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[1] , V[1] ] == {{0, (mW*FR$deltaZ[{Chi1, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi1, H}, {{}}])/2}},

C[ S[1] , -U[2] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi1, H}, {{}}]}},

C[ S[1] , -U[3] , U[2] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi1, H}, {{}}]}},

C[ S[2] , V[2] ] == {{0, (mW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/2}},

C[ S[2] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, Chi1}, {{}}]}},

C[ S[2] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, Chi1}, {{}}]}},

C[ S[2] , S[2] , S[3] , S[4] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[3] , S[3] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] ] == {{0, (-1/2*I)*mW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[1] ] == {{0, (-I)*lambda*vH*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[4] , V[2] ] == {{0, (mW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}]))/2}},

C[ S[4] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, Chi3}, {{}}]}},

C[ S[2] , S[2] , S[3] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[3] , S[3] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[4] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi2, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi2}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[3] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi2, H}, {{}}] + 3*FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[1] , V[2] ] == {{0, (mW*FR$deltaZ[{Chi2, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi2, H}, {{}}])/2}},

C[ S[1] , -U[1] , U[3] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi2, H}, {{}}]}},

C[ S[1] , -U[3] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi2, H}, {{}}]}},

C[ S[2] , V[3] ] == {{0, (mW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{W1, W3}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{W1, W3}, {{}}]))/2}},

C[ S[2] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, Chi1}, {{}}]}},

C[ S[2] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, Chi1}, {{}}]}},

C[ S[3] , V[3] ] == {{0, (mW*(FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/2}, {0, (mW*(FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/2}},

C[ S[3] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, Chi2}, {{}}]}},

C[ S[3] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[3] , S[3] , S[4] , S[1] ] == {{0, (-I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[4] , S[4] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] , S[1] , S[1] ] == {{0, (-3*I)*lambda*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] ] == {{0, (-1/2*I)*(mW^2*FR$deltaZ[{Chi3, H}, {{}}] + mh^2*FR$deltaZ[{H, Chi3}, {{}}])}, {0, (-1/2*I)*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[4] , S[1] , S[1] ] == {{0, (-I)*lambda*vH*(2*FR$deltaZ[{Chi3, H}, {{}}] + 3*FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[1] , V[3] ] == {{0, (mW*FR$deltaZ[{Chi3, H}, {{}}])/2}, {0, (mW*FR$deltaZ[{Chi3, H}, {{}}])/2}},

C[ S[1] , -U[1] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{Chi3, H}, {{}}]}},

C[ S[1] , -U[2] , U[1] ] == {{0, (I/8)*gW^2*vH*FR$deltaZ[{Chi3, H}, {{}}]}},

C[ S[2] , S[2] , S[2] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[3] , S[3] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[4] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[2] , S[2] , S[3] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , S[3] , S[3] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , S[4] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[3] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[2] , S[2] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[3] , S[3] , S[4] ] == {{0, (-I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , S[4] , S[4] ] == {{0, (-3*I)*lambda*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[1] , U[1] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[2] , U[2] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[4] , -U[3] , U[3] ] == {{0, (-1/8*I)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[2] ] == {{0, (-1/2*I)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ -U[2] , U[3] , V[2] ] == {{0, (gW*FR$deltaZ[{W1, W2}, {{}}])/2}, {0, (gW*FR$deltaZ[{W1, W2}, {{}}])/2}, {0, 0}},

C[ -U[3] , U[2] , V[2] ] == {{0, -1/2*(gW*FR$deltaZ[{W1, W2}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W1, W2}, {{}}])}, {0, 0}},

C[ V[1] , V[3] ] == {{0, (-1/2*I)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ -U[2] , U[3] , V[3] ] == {{0, (gW*FR$deltaZ[{W1, W3}, {{}}])/2}, {0, (gW*FR$deltaZ[{W1, W3}, {{}}])/2}, {0, 0}},

C[ -U[3] , U[2] , V[3] ] == {{0, -1/2*(gW*FR$deltaZ[{W1, W3}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W1, W3}, {{}}])}, {0, 0}},

C[ -U[1] , U[3] , V[1] ] == {{0, -1/2*(gW*FR$deltaZ[{W2, W1}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W2, W1}, {{}}])}, {0, 0}},

C[ -U[3] , U[1] , V[1] ] == {{0, (gW*FR$deltaZ[{W2, W1}, {{}}])/2}, {0, (gW*FR$deltaZ[{W2, W1}, {{}}])/2}, {0, 0}},

C[ V[2] , V[3] ] == {{0, (-1/2*I)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*mW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ -U[1] , U[3] , V[3] ] == {{0, -1/2*(gW*FR$deltaZ[{W2, W3}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W2, W3}, {{}}])}, {0, 0}},

C[ -U[3] , U[1] , V[3] ] == {{0, (gW*FR$deltaZ[{W2, W3}, {{}}])/2}, {0, (gW*FR$deltaZ[{W2, W3}, {{}}])/2}, {0, 0}},

C[ -U[1] , U[2] , V[1] ] == {{0, (gW*FR$deltaZ[{W3, W1}, {{}}])/2}, {0, (gW*FR$deltaZ[{W3, W1}, {{}}])/2}, {0, 0}},

C[ -U[2] , U[1] , V[1] ] == {{0, -1/2*(gW*FR$deltaZ[{W3, W1}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W3, W1}, {{}}])}, {0, 0}},

C[ -U[1] , U[2] , V[2] ] == {{0, (gW*FR$deltaZ[{W3, W2}, {{}}])/2}, {0, (gW*FR$deltaZ[{W3, W2}, {{}}])/2}, {0, 0}},

C[ -U[2] , U[1] , V[2] ] == {{0, -1/2*(gW*FR$deltaZ[{W3, W2}, {{}}])}, {0, -1/2*(gW*FR$deltaZ[{W3, W2}, {{}}])}, {0, 0}},

C[ S[2] , S[1] , V[1] ] == {{-gc139, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(4*mW*vH)}, {gc139, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[1] ] == {{-gc140, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}, {gc140, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(4*mW*vH)}},

C[ S[3] , S[1] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] - FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] - FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W2, W1}, {{}}]))}},

C[ S[4] , S[1] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{W3, W1}, {{}}]))}},

C[ S[2] , S[4] , V[1] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] - FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W2, W1}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] - FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W2, W1}, {{}}]))/4}},

C[ S[2] , S[3] , V[1] ] == {{0, (gW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W3, W1}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi3, Chi1}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W3, W1}, {{}}]))}},

C[ S[2] , S[2] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/(mW*vH)}},

C[ S[1] , V[1] , V[1] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W1, W1}, {{}}]))/mW}},

C[ S[2] , S[3] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[1] , V[1] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[1] , V[1] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ S[2] , S[4] , V[2] ] == {{-gc159, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(4*mW*vH)}, {gc159, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[1] , V[2] ] == {{-gc160, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(4*mW*vH)}, {gc160, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W1, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}] - FR$deltaZ[{W1, W2}, {{}}]))}},

C[ S[4] , S[1] , V[2] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi1, H}, {{}}] - FR$deltaZ[{Chi2, Chi3}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi1, H}, {{}}] - FR$deltaZ[{Chi2, Chi3}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))/4}},

C[ S[2] , S[1] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi1}, {{}}] + FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{W1, W2}, {{}}]))}},

C[ S[2] , S[3] , V[2] ] == {{0, (gW*(FR$deltaZ[{Chi3, Chi2}, {{}}] - FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi3, Chi2}, {{}}] - FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W3, W2}, {{}}]))}},

C[ S[2] , S[2] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[3] , S[3] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[4] , S[4] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ S[1] , V[1] , V[2] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ V[1] , V[2] , V[3] ] == {{-gc170, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc170, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc170, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {-gc170, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {-gc170, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(2*mW*vH)}, {gc170, -1/2*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[1] , V[2] , V[2] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/mW}},

C[ S[2] , S[3] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[2] , V[2] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[2] , V[2] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[1] , V[2] , V[2] ] == {{(-I)*gc185, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {(-I)*gc185, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}, {(2*I)*gc185, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}]))/(mW*vH)}},

C[ S[2] , S[3] , V[3] ] == {{-gc186, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {gc186, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(4*mW*vH)}},

C[ S[4] , S[1] , V[3] ] == {{-gc187, (gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(4*mW*vH)}, {gc187, -1/4*(gW*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[3] , S[4] , V[3] ] == {{0, (gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] - FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, Chi3}, {{}}] - FR$deltaZ[{H, Chi2}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))}},

C[ S[3] , S[1] , V[3] ] == {{0, (gW*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))/4}, {0, -1/4*(gW*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}] + FR$deltaZ[{W2, W3}, {{}}]))}},

C[ S[2] , S[4] , V[3] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W2, W3}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}] - FR$deltaZ[{W2, W3}, {{}}]))/4}},

C[ S[2] , S[1] , V[3] ] == {{0, -1/4*(gW*(FR$deltaZ[{Chi2, H}, {{}}] - FR$deltaZ[{Chi3, Chi1}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))}, {0, (gW*(FR$deltaZ[{Chi2, H}, {{}}] - FR$deltaZ[{Chi3, Chi1}, {{}}] - FR$deltaZ[{W1, W3}, {{}}]))/4}},

C[ S[2] , S[2] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[3] , S[3] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[4] , S[4] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[1] , S[1] , V[1] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[1] , V[1] , V[3] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[2] , S[2] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[3] , S[3] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[4] , S[4] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[1] , S[1] , V[2] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ S[1] , V[2] , V[3] ] == {{0, (I/4)*gW^2*vH*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ V[1] , V[1] , V[2] , V[3] ] == {{0, (I/2)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}, {0, (-I)*gW^2*(FR$deltaZ[{W2, W3}, {{}}] + FR$deltaZ[{W3, W2}, {{}}])}},

C[ V[1] , V[2] , V[2] , V[3] ] == {{0, (-I)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W3}, {{}}] + FR$deltaZ[{W3, W1}, {{}}])}},

C[ S[2] , S[2] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi1, Chi1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[3] , S[3] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi2, Chi2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[4] , S[4] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{Chi3, Chi3}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[1] , S[1] , V[3] , V[3] ] == {{(I/2)*gW^2, ((I/2)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ S[1] , V[3] , V[3] ] == {{(I/2)*gW^2*vH, ((I/4)*gW^2*(4*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{H, H}, {{}}] + 2*mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/mW}},

C[ S[2] , S[3] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi2}, {{}}] + FR$deltaZ[{Chi2, Chi1}, {{}}])}},

C[ S[2] , S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi1}, {{}}])}},

C[ S[2] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi1, H}, {{}}] + FR$deltaZ[{H, Chi1}, {{}}])}},

C[ S[3] , S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, Chi3}, {{}}] + FR$deltaZ[{Chi3, Chi2}, {{}}])}},

C[ S[3] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi2, H}, {{}}] + FR$deltaZ[{H, Chi2}, {{}}])}},

C[ S[4] , S[1] , V[3] , V[3] ] == {{0, (I/4)*gW^2*(FR$deltaZ[{Chi3, H}, {{}}] + FR$deltaZ[{H, Chi3}, {{}}])}},

C[ S[2] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi1}, {{}}]}},

C[ S[3] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi2}, {{}}]}},

C[ S[4] , V[3] , V[3] ] == {{0, (I/4)*gW^2*vH*FR$deltaZ[{H, Chi3}, {{}}]}},

C[ V[1] , V[1] , V[3] , V[3] ] == {{(-I)*gc218, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(-I)*gc218, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(2*I)*gc218, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W1, W1}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}},

C[ V[1] , V[2] , V[3] , V[3] ] == {{0, (I/2)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (I/2)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}, {0, (-I)*gW^2*(FR$deltaZ[{W1, W2}, {{}}] + FR$deltaZ[{W2, W1}, {{}}])}},

C[ V[2] , V[2] , V[3] , V[3] ] == {{(-I)*gc220, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(-I)*gc220, (I*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}, {(2*I)*gc220, ((-2*I)*gW^2*(2*vH*FR$delta[{mW}, {}] - 2*mW*FR$delta[{vH}, {}] + mW*vH*FR$deltaZ[{W2, W2}, {{}}] + mW*vH*FR$deltaZ[{W3, W3}, {{}}]))/(mW*vH)}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc28 -> gW,
     gc30 -> -gW,
     gc32 -> -gW,
     gc36 -> gW,
     gc38 -> gW,
     gc40 -> -gW,
     gc139 -> -1/2*gW,
     gc140 -> gW/2,
     gc159 -> -1/2*gW,
     gc160 -> -1/2*gW,
     gc170 -> -gW,
     gc185 -> -gW^2,
     gc186 -> gW/2,
     gc187 -> -1/2*gW,
     gc218 -> -gW^2,
     gc220 -> -gW^2};

