(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"QED Broad Resonance",
  Authors -> {"S.Song"},
  Version -> "1.0",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"},
  Date -> "20, Jan, 2025"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{New, 0}, {QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Phi",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MPhi,
    Indices -> {} },

S[2] == {
    SelfConjugate -> False,
    PropagatorLabel -> "chi",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> Mchi,
    Indices -> {} },

F[2] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {Q},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mlep },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} }
}


(*        Definitions       *)


MPhi[ ___ ] := MPhi;
Mchi[ ___ ] := Mchi;
Mlep[ 1 ] := FCGV["ME"];
Mlep[ 2 ] := FCGV["MM"];
Mlep[ 3 ] := FCGV["ML"];


TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , -S[2] , S[1] ] == {{(-I)*ys, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc2*IndexDelta[e1x2, e2x2], 0}, {I*gc2*IndexDelta[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc3*IndexDelta[e1x2, e2x2], 0}, {I*gc3*IndexDelta[e1x2, e2x2], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc2 -> -yl,
     gc3 -> EE};

