(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SQED",
  Authors -> {"S. Song"},
  Version -> "1.0.0",
  Institutions -> {"Seoul National University"},
  Emails -> {"hypercube256@snu.ac.kr"},
  Date -> "24 July 2016"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Phi",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mPhi,
    Indices -> {} },

V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} }
}


(*        Definitions       *)


mPhi[ ___ ] := mPhi;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , -S[1] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[1] , -S[1] , V[1] ] == {{(-I)*gc2, 0}, {I*gc2, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc2 -> -FCGV["EL"]};

